
// Generated by Cadence Genus(TM) Synthesis Solution GENUS15.20 - 15.20-p004_1
// Generated on: May 24 2025 16:38:57

// Verification Directory fv/synth_wrapper 

module d_flipflop_27(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_1 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_19(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_1 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_20(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_1 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_21(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_1 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_22(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_1 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_23(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_1 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_24(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_1 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_25(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_1 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_26(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_1 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module register_8bit_2(clk, rstn, d, q);
  input clk, rstn;
  input [7:0] d;
  output [7:0] q;
  wire clk, rstn;
  wire [7:0] d;
  wire [7:0] q;
  d_flipflop_19 bit0(.clk (clk), .rstn (rstn), .d (d[0]), .q (q[0]));
  d_flipflop_20 bit1(.clk (clk), .rstn (rstn), .d (d[1]), .q (q[1]));
  d_flipflop_21 bit2(.clk (clk), .rstn (rstn), .d (d[2]), .q (q[2]));
  d_flipflop_22 bit3(.clk (clk), .rstn (rstn), .d (d[3]), .q (q[3]));
  d_flipflop_23 bit4(.clk (clk), .rstn (rstn), .d (d[4]), .q (q[4]));
  d_flipflop_24 bit5(.clk (clk), .rstn (rstn), .d (d[5]), .q (q[5]));
  d_flipflop_25 bit6(.clk (clk), .rstn (rstn), .d (d[6]), .q (q[6]));
  d_flipflop_26 bit7(.clk (clk), .rstn (rstn), .d (d[7]), .q (q[7]));
endmodule

module d_flipflop(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_1 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_1(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_2 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_2(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_2 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_3(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_1 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_4(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_2 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_5(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_1 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_6(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_2 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_7(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_2 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module register_8bit(clk, rstn, d, q);
  input clk, rstn;
  input [7:0] d;
  output [7:0] q;
  wire clk, rstn;
  wire [7:0] d;
  wire [7:0] q;
  d_flipflop bit0(clk, rstn, d[0], q[0]);
  d_flipflop_1 bit1(clk, rstn, d[1], q[1]);
  d_flipflop_2 bit2(clk, rstn, d[2], q[2]);
  d_flipflop_3 bit3(clk, rstn, d[3], q[3]);
  d_flipflop_4 bit4(clk, rstn, d[4], q[4]);
  d_flipflop_5 bit5(clk, rstn, d[5], q[5]);
  d_flipflop_6 bit6(clk, rstn, d[6], q[6]);
  d_flipflop_7 bit7(clk, rstn, d[7], q[7]);
endmodule

module d_flipflop_11(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_1 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_12(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_1 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_13(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_2 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_14(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_1 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_15(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_1 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_16(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_1 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_17(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_1 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_18(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_1 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module register_8bit_1(clk, rstn, d, q);
  input clk, rstn;
  input [7:0] d;
  output [7:0] q;
  wire clk, rstn;
  wire [7:0] d;
  wire [7:0] q;
  d_flipflop_11 bit0(.clk (clk), .rstn (rstn), .d (d[0]), .q (q[0]));
  d_flipflop_12 bit1(.clk (clk), .rstn (rstn), .d (d[1]), .q (q[1]));
  d_flipflop_13 bit2(.clk (clk), .rstn (rstn), .d (d[2]), .q (q[2]));
  d_flipflop_14 bit3(.clk (clk), .rstn (rstn), .d (d[3]), .q (q[3]));
  d_flipflop_15 bit4(.clk (clk), .rstn (rstn), .d (d[4]), .q (q[4]));
  d_flipflop_16 bit5(.clk (clk), .rstn (rstn), .d (d[5]), .q (q[5]));
  d_flipflop_17 bit6(.clk (clk), .rstn (rstn), .d (d[6]), .q (q[6]));
  d_flipflop_18 bit7(.clk (clk), .rstn (rstn), .d (d[7]), .q (q[7]));
endmodule

module d_flipflop_8(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_1 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_9(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_1 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_10(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_1 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module register_3bit(clk, rstn, d, q);
  input clk, rstn;
  input [2:0] d;
  output [2:0] q;
  wire clk, rstn;
  wire [2:0] d;
  wire [2:0] q;
  d_flipflop_8 bit0(clk, rstn, d[0], q[0]);
  d_flipflop_9 bit1(clk, rstn, d[1], q[1]);
  d_flipflop_10 bit2(clk, rstn, d[2], q[2]);
endmodule

module alu_8bit(i_clk, i_rstn, i_a, i_b, i_op_sel, o_result, o_carry);
  input i_clk, i_rstn;
  input [7:0] i_a, i_b;
  input [2:0] i_op_sel;
  output [7:0] o_result;
  output o_carry;
  wire i_clk, i_rstn;
  wire [7:0] i_a, i_b;
  wire [2:0] i_op_sel;
  wire [7:0] o_result;
  wire o_carry;
  wire [7:0] result_d;
  wire [7:0] A;
  wire [7:0] B;
  wire [2:0] op_sel;
  wire n_2, n_10, n_21, n_23, n_24, n_26, n_29, n_32;
  wire n_34, n_35, n_43, n_44, n_47, n_48, n_50, n_52;
  wire n_60, n_61, n_63, n_64, n_68, n_69, n_70, n_71;
  wire n_73, n_74, n_77, n_78, n_84, n_94, n_95, n_98;
  wire n_99, n_101, n_103, n_104, n_105, n_106, n_107, n_108;
  wire n_109, n_110, n_112, n_113, n_115, n_123, n_129, n_141;
  wire n_146, n_147, n_148, n_149, n_150, n_151, n_153, n_159;
  wire n_160, n_161, n_163, n_164, n_165, n_166, n_167, n_168;
  wire n_172, n_173, n_177, n_178, n_181, n_183, n_184, n_194;
  wire n_204, n_206, n_209, n_210, n_216, n_218, n_224, n_226;
  wire n_232, n_240, n_243, n_250, n_254, n_267, n_271, n_273;
  wire n_366, n_370, n_371, n_387, n_400, n_401, n_416, n_417;
  wire n_418, n_450, n_458, n_459, n_481, n_501, n_502, n_505;
  wire n_529, n_532, n_533, n_541, n_542, n_544, n_575, n_607;
  wire n_634, n_637, n_638, n_640, n_644, n_652, n_659, n_665;
  wire n_667, n_669, n_672, n_705, n_717, n_720, n_723, n_724;
  wire n_725, n_727, n_770, n_782, n_783, n_797, n_827, n_828;
  wire n_830, n_831, n_832, n_833, n_834, n_835, n_836, n_875;
  wire n_878, n_886, n_920, n_921, n_923, n_924, n_926, n_927;
  wire n_928, n_929, n_940, n_941, n_942, n_957, n_958, n_959;
  wire n_965, n_966, n_967, n_968, n_974, n_981, n_987, n_1010;
  wire n_1014, n_1015, n_1025, n_1028, n_1030, n_1061, n_1062, n_1065;
  wire n_1067, n_1069, n_1107, n_1113, n_1115, n_1122, n_1123, n_1124;
  wire n_1129, n_1130, n_1138, n_1139, n_1142, n_1144, n_1145, n_1151;
  wire n_1152, n_1153, n_1163, n_1164, n_1165, n_1167, n_1168, n_1170;
  wire n_1171, n_1176, n_1177, n_1178, n_1190, n_1191, n_1194, n_1200;
  wire n_1210, n_1211, n_1218, n_1222, n_1223, n_1224, n_1225, n_1226;
  wire n_1227, n_1230, n_1231, n_1233, n_1234, n_1235, n_1236, n_1239;
  wire n_1240, n_1241, n_1246, n_1249, n_1250, n_1251, n_1252, n_1253;
  wire n_1255, n_1257, n_1271, n_1272, n_1273, n_1282, n_1283, n_1355;
  wire n_1356, n_1405, n_1408, n_1410, n_1411, n_1413, n_1423, n_1449;
  wire n_1451, n_1459, n_1460, n_1461, n_1462, n_1463, n_1466, n_1467;
  wire n_1468, n_1469, n_1470, n_1471, n_1472, n_1473, n_1474, n_1475;
  wire n_1477, n_1478, n_1506, n_1507, n_1508, n_1509, n_1510, n_1512;
  wire n_1514, n_1515, n_1516, n_1527, n_1528, n_1548, n_1549, n_1578;
  wire n_1579, n_1580, n_1581, n_1600, n_1601, n_1602, n_1603, n_1605;
  wire n_1608, n_1609, n_1611, n_1612, n_1613, n_1614, n_1615, n_1620;
  wire n_1621, n_1622, n_1623, n_1624, n_1627, n_1628, n_1629, n_1630;
  wire n_1643, n_1645, n_1651, n_1652, n_1653, n_1654, n_1655, n_1656;
  wire n_1657, n_1658, n_1659, n_1660, n_1661, n_1663, n_1664, n_1665;
  wire n_1666, n_1668, n_1669, n_1670, n_1671, n_1672, n_1673, n_1674;
  wire n_1683, n_1684, n_1686, n_1688, n_1690, n_1731, n_1732, n_1737;
  wire n_1738, n_1739, n_1740, n_1742, n_1743, n_1744, n_1778, n_1779;
  wire n_1780, n_1781, n_1793, n_1794, n_1795, n_1796, n_1862, n_1872;
  wire n_1873, n_1874, n_1875, n_1876, n_1877, n_1878, n_1879, n_1880;
  wire n_1881, n_1883, n_1884, n_1887, n_1888, n_1889, n_1892, n_1894;
  wire n_1904, n_1906, n_1907, n_1908, n_1909, n_1910, n_1913, n_1915;
  wire n_1916, n_1918, n_1919, n_1921, n_1922, n_1924, n_1925, n_1926;
  wire n_1927, n_1928, n_1929, n_1930, n_1931, n_1932;
  d_flipflop_27 Cout_buff(i_clk, i_rstn, n_1030, o_carry);
  register_8bit_2 S_buff(i_clk, i_rstn, {n_1796, n_1477, n_1744, n_720,
       result_d[3], n_1623, result_d[1], n_1528}, o_result);
  register_8bit fetch_A(i_clk, i_rstn, i_a, A);
  register_8bit_1 fetch_B(i_clk, i_rstn, i_b, B);
  register_3bit fetch_op(i_clk, i_rstn, {n_400, i_op_sel[1], n_458},
       op_sel);
  sky130_fd_sc_hd__nand3_1 g23295(.A (n_942), .B (n_1062), .C (n_659),
       .Y (result_d[3]));
  sky130_fd_sc_hd__o21ai_1 g23319(.A1 (n_665), .A2 (n_727), .B1 (n_10),
       .Y (result_d[1]));
  sky130_fd_sc_hd__o21ai_2 g23339(.A1 (n_1880), .A2 (n_1657), .B1
       (n_148), .Y (n_273));
  sky130_fd_sc_hd__o21a_1 g23342(.A1 (n_1906), .A2 (n_1460), .B1
       (n_640), .X (n_271));
  sky130_fd_sc_hd__nand2_1 g23345(.A (n_1478), .B (n_1231), .Y (n_267));
  sky130_fd_sc_hd__inv_1 g23362(.A (n_1657), .Y (n_254));
  sky130_fd_sc_hd__nand2_2 g23367(.A (n_1906), .B (n_1462), .Y (n_250));
  sky130_fd_sc_hd__xnor2_1 g23375(.A (n_370), .B (n_1661), .Y (n_243));
  sky130_fd_sc_hd__o21ai_1 g23378(.A1 (n_172), .A2 (n_1230), .B1
       (n_165), .Y (n_240));
  sky130_fd_sc_hd__nand2_1 g23394(.A (n_204), .B (n_1739), .Y (n_232));
  sky130_fd_sc_hd__nand2_1 g23400(.A (n_210), .B (n_216), .Y (n_226));
  sky130_fd_sc_hd__o2111ai_1 g23402(.A1 (n_24), .A2 (n_1227), .B1
       (n_150), .C1 (n_149), .D1 (n_168), .Y (n_224));
  sky130_fd_sc_hd__nor2_1 g23415(.A (n_1738), .B (n_1283), .Y (n_210));
  sky130_fd_sc_hd__o2111a_1 g23416(.A1 (A[1]), .A2 (n_106), .B1 (n_2),
       .C1 (n_109), .D1 (n_105), .X (n_209));
  sky130_fd_sc_hd__o21ai_1 g23419(.A1 (A[2]), .A2 (n_107), .B1 (n_166),
       .Y (n_206));
  sky130_fd_sc_hd__nor2_1 g23421(.A (n_575), .B (n_1283), .Y (n_218));
  sky130_fd_sc_hd__nand2_2 g23422(.A (n_160), .B (n_177), .Y (n_216));
  sky130_fd_sc_hd__o2bb2ai_1 g23427(.A1_N (n_1872), .A2_N (n_147), .B1
       (A[6]), .B2 (n_1227), .Y (n_194));
  sky130_fd_sc_hd__o21ai_2 g23430(.A1 (n_1272), .A2 (n_141), .B1
       (n_167), .Y (n_204));
  sky130_fd_sc_hd__nand2_2 g23445(.A (n_1122), .B (n_1506), .Y (n_184));
  sky130_fd_sc_hd__nand2_2 g23446(.A (n_542), .B (n_1014), .Y (n_183));
  sky130_fd_sc_hd__nand2_1 g23448(.A (n_153), .B (A[1]), .Y (n_181));
  sky130_fd_sc_hd__nand2_1 g23452(.A (n_417), .B (n_1506), .Y (n_178));
  sky130_fd_sc_hd__nand2_1 g23454(.A (n_1122), .B (n_1014), .Y (n_177));
  sky130_fd_sc_hd__inv_1 g23456(.A (n_172), .Y (n_173));
  sky130_fd_sc_hd__a22oi_1 g23458(.A1 (n_94), .A2 (n_1930), .B1 (n_64),
       .B2 (n_129), .Y (n_168));
  sky130_fd_sc_hd__nand2_1 g23459(.A (n_974), .B (n_1272), .Y (n_167));
  sky130_fd_sc_hd__a32oi_1 g23460(.A1 (n_99), .A2 (n_29), .A3 (A[2]),
       .B1 (n_103), .B2 (n_64), .Y (n_166));
  sky130_fd_sc_hd__a32oi_1 g23461(.A1 (n_99), .A2 (n_35), .A3 (A[7]),
       .B1 (n_113), .B2 (n_44), .Y (n_165));
  sky130_fd_sc_hd__a32oi_1 g23462(.A1 (n_99), .A2 (n_26), .A3 (n_981),
       .B1 (n_115), .B2 (n_43), .Y (n_164));
  sky130_fd_sc_hd__nand2_1 g23463(.A (n_63), .B (n_1509), .Y (n_163));
  sky130_fd_sc_hd__nor2_1 g23465(.A (n_44), .B (n_387), .Y (n_161));
  sky130_fd_sc_hd__nand2_1 g23467(.A (n_1509), .B (n_1506), .Y (n_160));
  sky130_fd_sc_hd__nand2_1 g23470(.A (n_1507), .B (n_1509), .Y (n_172));
  sky130_fd_sc_hd__o21ai_1 g23478(.A1 (n_1872), .A2 (n_98), .B1
       (n_529), .Y (n_151));
  sky130_fd_sc_hd__o21ai_1 g23479(.A1 (n_24), .A2 (n_1272), .B1
       (n_101), .Y (n_150));
  sky130_fd_sc_hd__nand2_1 g23480(.A (n_99), .B (n_94), .Y (n_149));
  sky130_fd_sc_hd__a31oi_2 g23481(.A1 (n_64), .A2 (A[7]), .A3 (n_34),
       .B1 (n_110), .Y (n_148));
  sky130_fd_sc_hd__o221ai_1 g23482(.A1 (A[6]), .A2 (n_77), .B1 (n_60),
       .B2 (n_1253), .C1 (n_529), .Y (n_147));
  sky130_fd_sc_hd__o2bb2ai_1 g23483(.A1_N (n_73), .A2_N (n_84), .B1
       (n_981), .B2 (n_69), .Y (n_146));
  sky130_fd_sc_hd__nand2_2 g23488(.A (n_1629), .B (n_70), .Y (n_153));
  sky130_fd_sc_hd__inv_2 g23489(.A (n_417), .Y (n_141));
  sky130_fd_sc_hd__inv_1 g23506(.A (n_70), .Y (n_129));
  sky130_fd_sc_hd__nand2_1 g23512(.A (n_418), .B (A[7]), .Y (n_123));
  sky130_fd_sc_hd__o21ai_1 g23520(.A1 (n_26), .A2 (n_77), .B1 (n_1227),
       .Y (n_115));
  sky130_fd_sc_hd__o21ai_1 g23522(.A1 (n_35), .A2 (n_77), .B1 (n_1227),
       .Y (n_113));
  sky130_fd_sc_hd__o21a_1 g23523(.A1 (n_827), .A2 (n_77), .B1 (n_1227),
       .X (n_112));
  sky130_fd_sc_hd__a21oi_1 g23525(.A1 (n_35), .A2 (n_44), .B1 (n_529),
       .Y (n_110));
  sky130_fd_sc_hd__o21ai_1 g23526(.A1 (A[1]), .A2 (n_32), .B1 (n_101),
       .Y (n_109));
  sky130_fd_sc_hd__o21ai_1 g23527(.A1 (A[4]), .A2 (n_21), .B1 (n_101),
       .Y (n_108));
  sky130_fd_sc_hd__o21a_1 g23528(.A1 (n_29), .A2 (n_77), .B1 (n_1227),
       .X (n_107));
  sky130_fd_sc_hd__o21a_1 g23529(.A1 (n_1190), .A2 (n_77), .B1
       (n_1227), .X (n_106));
  sky130_fd_sc_hd__nand3_1 g23530(.A (n_99), .B (n_1190), .C (A[1]), .Y
       (n_105));
  sky130_fd_sc_hd__nand3_1 g23531(.A (n_99), .B (n_827), .C (A[4]), .Y
       (n_104));
  sky130_fd_sc_hd__maj3_1 g23532(.A (A[2]), .B (B[2]), .C (op_sel[0]),
       .X (n_103));
  sky130_fd_sc_hd__inv_2 g23533(.A (n_529), .Y (n_101));
  sky130_fd_sc_hd__inv_1 g23536(.A (n_99), .Y (n_98));
  sky130_fd_sc_hd__nand3_1 g23539(.A (n_64), .B (A[4]), .C (n_21), .Y
       (n_95));
  sky130_fd_sc_hd__nor2_4 g23542(.A (op_sel[0]), .B (n_77), .Y (n_99));
  sky130_fd_sc_hd__o21ai_1 g23559(.A1 (n_981), .A2 (n_47), .B1 (n_69),
       .Y (n_84));
  sky130_fd_sc_hd__xnor2_1 g23563(.A (n_24), .B (n_1014), .Y (n_94));
  sky130_fd_sc_hd__clkinv_2 g23568(.A (n_78), .Y (n_77));
  sky130_fd_sc_hd__nand2_1 g23570(.A (i_op_sel[0]), .B (n_1190), .Y
       (n_74));
  sky130_fd_sc_hd__and2_4 g23575(.A (n_1250), .B (op_sel[2]), .X
       (n_78));
  sky130_fd_sc_hd__inv_1 g23577(.A (n_68), .Y (n_69));
  sky130_fd_sc_hd__inv_2 g23579(.A (n_1253), .Y (n_64));
  sky130_fd_sc_hd__nor2_1 g23580(.A (n_1191), .B (n_1272), .Y (n_63));
  sky130_fd_sc_hd__nor2_1 g23582(.A (n_32), .B (n_29), .Y (n_71));
  sky130_fd_sc_hd__nand2_1 g23583(.A (A[0]), .B (B[0]), .Y (n_70));
  sky130_fd_sc_hd__and2_1 g23584(.A (n_26), .B (n_1251), .X (n_68));
  sky130_fd_sc_hd__inv_1 g23593(.A (n_35), .Y (n_34));
  sky130_fd_sc_hd__clkinv_1 g23595(.A (B[7]), .Y (n_35));
  sky130_fd_sc_hd__inv_1 g23596(.A (A[5]), .Y (n_61));
  sky130_fd_sc_hd__inv_1 g23597(.A (A[6]), .Y (n_60));
  sky130_fd_sc_hd__clkinv_1 g23613(.A (n_1190), .Y (n_32));
  sky130_fd_sc_hd__inv_4 g23621(.A (B[2]), .Y (n_29));
  sky130_fd_sc_hd__inv_2 g23641(.A (i_op_sel[1]), .Y (n_52));
  sky130_fd_sc_hd__inv_4 g23647(.A (B[3]), .Y (n_26));
  sky130_fd_sc_hd__inv_2 g23648(.A (n_1252), .Y (n_50));
  sky130_fd_sc_hd__inv_2 g23651(.A (n_24), .Y (n_48));
  sky130_fd_sc_hd__buf_1 g23652(.A (A[0]), .X (n_24));
  sky130_fd_sc_hd__inv_2 g23653(.A (n_1887), .Y (n_47));
  sky130_fd_sc_hd__buf_1 g23656(.A (n_1251), .X (n_23));
  sky130_fd_sc_hd__inv_2 g23664(.A (n_827), .Y (n_21));
  sky130_fd_sc_hd__inv_2 g23672(.A (A[7]), .Y (n_44));
  sky130_fd_sc_hd__o211a_1 g23689(.A1 (n_965), .A2 (n_243), .B1
       (n_209), .C1 (n_226), .X (n_10));
  sky130_fd_sc_hd__nand3b_1 g23697(.A_N (n_1191), .B (n_64), .C (A[1]),
       .Y (n_2));
  sky130_fd_sc_hd__inv_1 g23700(.A (op_sel[0]), .Y (n_73));
  sky130_fd_sc_hd__xnor2_1 g9(.A (A[5]), .B (n_836), .Y (n_366));
  sky130_fd_sc_hd__clkinv_1 g23731(.A (n_153), .Y (n_370));
  sky130_fd_sc_hd__inv_2 g23732(.A (A[1]), .Y (n_371));
  sky130_fd_sc_hd__xor2_1 g23746(.A (n_34), .B (n_1411), .X (n_387));
  sky130_fd_sc_hd__inv_1 fopt23760(.A (n_401), .Y (n_400));
  sky130_fd_sc_hd__inv_2 fopt23761(.A (i_op_sel[2]), .Y (n_401));
  sky130_fd_sc_hd__o21ai_2 g23773(.A1 (n_43), .A2 (n_1223), .B1
       (n_416), .Y (n_417));
  sky130_fd_sc_hd__nand2_1 g23775(.A (n_1223), .B (A[4]), .Y (n_416));
  sky130_fd_sc_hd__inv_2 g23776(.A (n_1223), .Y (n_418));
  sky130_fd_sc_hd__xnor2_1 g23811(.A (A[6]), .B (n_1872), .Y (n_450));
  sky130_fd_sc_hd__inv_1 fopt23819(.A (n_459), .Y (n_458));
  sky130_fd_sc_hd__inv_1 fopt23820(.A (i_op_sel[0]), .Y (n_459));
  sky130_fd_sc_hd__xor2_1 g23840(.A (A[7]), .B (n_35), .X (n_481));
  sky130_fd_sc_hd__o21ai_2 g23857(.A1 (n_1249), .A2 (n_1165), .B1
       (n_501), .Y (n_502));
  sky130_fd_sc_hd__nand2_1 g23859(.A (n_1165), .B (A[5]), .Y (n_501));
  sky130_fd_sc_hd__nand2_2 g23862(.A (n_1165), .B (A[6]), .Y (n_505));
  sky130_fd_sc_hd__nand3_1 g23888(.A (n_1251), .B (op_sel[0]), .C
       (n_1252), .Y (n_529));
  sky130_fd_sc_hd__nand2_1 g23890(.A (n_529), .B (n_532), .Y (n_533));
  sky130_fd_sc_hd__nand2_1 g23891(.A (n_833), .B (n_64), .Y (n_532));
  sky130_fd_sc_hd__o21ai_1 g23901(.A1 (n_48), .A2 (n_1171), .B1
       (n_541), .Y (n_542));
  sky130_fd_sc_hd__nand2_1 g23903(.A (n_1171), .B (A[7]), .Y (n_541));
  sky130_fd_sc_hd__inv_2 g29(.A (n_1601), .Y (n_634));
  sky130_fd_sc_hd__a21oi_1 g23947(.A1 (n_637), .A2 (n_638), .B1
       (n_1226), .Y (n_640));
  sky130_fd_sc_hd__nand2b_1 g23948(.A_N (n_533), .B (n_835), .Y
       (n_637));
  sky130_fd_sc_hd__inv_2 g23950(.A (n_61), .Y (n_638));
  sky130_fd_sc_hd__inv_1 g81(.A (n_74), .Y (n_644));
  sky130_fd_sc_hd__clkbuf_8 fopt23953(.A (n_1171), .X (n_544));
  sky130_fd_sc_hd__inv_2 g23954(.A (n_832), .Y (n_159));
  sky130_fd_sc_hd__nor2b_2 g23955(.A (n_544), .B_N (n_29), .Y (n_652));
  sky130_fd_sc_hd__nand2_1 g75(.A (n_218), .B (n_1581), .Y (n_659));
  sky130_fd_sc_hd__nand2_1 g15(.A (n_1171), .B (n_24), .Y (n_667));
  sky130_fd_sc_hd__nand2_2 g23964(.A (n_401), .B (n_52), .Y (n_669));
  sky130_fd_sc_hd__nor2_2 g23966(.A (n_459), .B (n_669), .Y (n_672));
  sky130_fd_sc_hd__nand2_1 g287(.A (n_161), .B (n_1688), .Y (n_705));
  sky130_fd_sc_hd__nand2_1 g214(.A (n_1674), .B (n_1240), .Y (n_720));
  sky130_fd_sc_hd__nor2_1 g218(.A (n_965), .B (n_1904), .Y (n_717));
  sky130_fd_sc_hd__a21oi_1 g241(.A1 (n_1478), .A2 (n_575), .B1
       (n_1282), .Y (n_727));
  sky130_fd_sc_hd__nand2_1 g243(.A (n_723), .B (n_1271), .Y (n_724));
  sky130_fd_sc_hd__nor2_1 g245(.A (n_1738), .B (n_1506), .Y (n_723));
  sky130_fd_sc_hd__nand3b_1 g244(.A_N (n_1738), .B (n_502), .C
       (n_1506), .Y (n_725));
  sky130_fd_sc_hd__nand2b_1 g554(.A_N (n_450), .B (n_1408), .Y (n_770));
  sky130_fd_sc_hd__inv_2 g24010(.A (i_op_sel[1]), .Y (n_782));
  sky130_fd_sc_hd__inv_2 g24011(.A (i_op_sel[2]), .Y (n_783));
  sky130_fd_sc_hd__nand2_2 g24019(.A (n_1690), .B (n_644), .Y (n_797));
  sky130_fd_sc_hd__inv_2 g60(.A (B[4]), .Y (n_827));
  sky130_fd_sc_hd__nand3_1 g51(.A (n_68), .B (n_831), .C (n_50), .Y
       (n_832));
  sky130_fd_sc_hd__and3b_1 g52(.A_N (B[5]), .B (n_830), .C (n_827), .X
       (n_831));
  sky130_fd_sc_hd__inv_2 g59(.A (B[5]), .Y (n_828));
  sky130_fd_sc_hd__nor2_1 g54(.A (B[7]), .B (B[6]), .Y (n_830));
  sky130_fd_sc_hd__nand2_1 g24033(.A (n_99), .B (n_834), .Y (n_835));
  sky130_fd_sc_hd__inv_1 g56(.A (n_833), .Y (n_834));
  sky130_fd_sc_hd__clkbuf_1 g57(.A (B[5]), .X (n_833));
  sky130_fd_sc_hd__inv_2 g55(.A (n_828), .Y (n_836));
  sky130_fd_sc_hd__nand3_2 g129(.A (n_1904), .B (n_968), .C (n_1906),
       .Y (n_878));
  sky130_fd_sc_hd__inv_2 fopt24046(.A (n_878), .Y (n_886));
  sky130_fd_sc_hd__nand2_4 g24074(.A (n_923), .B (A[5]), .Y (n_924));
  sky130_fd_sc_hd__nand2_2 g24075(.A (n_921), .B (n_1608), .Y (n_923));
  sky130_fd_sc_hd__nand2_2 g24076(.A (n_1609), .B (n_920), .Y (n_921));
  sky130_fd_sc_hd__inv_1 g24078(.A (n_836), .Y (n_920));
  sky130_fd_sc_hd__nand3_1 g24080(.A (n_1862), .B (n_1461), .C (n_924),
       .Y (n_926));
  sky130_fd_sc_hd__nand3_1 g24081(.A (n_924), .B (n_1925), .C (n_1461),
       .Y (n_927));
  sky130_fd_sc_hd__nand2_1 g24082(.A (n_928), .B (n_61), .Y (n_929));
  sky130_fd_sc_hd__inv_1 g24083(.A (n_923), .Y (n_928));
  sky130_fd_sc_hd__nand2_1 g24094(.A (n_940), .B (n_941), .Y (n_942));
  sky130_fd_sc_hd__nand3_2 g34(.A (n_1683), .B (n_1684), .C (n_47), .Y
       (n_940));
  sky130_fd_sc_hd__nor2_1 g24095(.A (n_50), .B (n_146), .Y (n_941));
  sky130_fd_sc_hd__nand2_1 g24103(.A (n_957), .B (n_958), .Y (n_959));
  sky130_fd_sc_hd__nand2_1 g86(.A (A[4]), .B (n_827), .Y (n_957));
  sky130_fd_sc_hd__nand2_1 g85(.A (n_875), .B (n_21), .Y (n_958));
  sky130_fd_sc_hd__inv_2 g88(.A (n_1930), .Y (n_965));
  sky130_fd_sc_hd__nand2_4 g24105(.A (n_250), .B (n_924), .Y (n_966));
  sky130_fd_sc_hd__clkinv_4 g24106(.A (n_967), .Y (n_968));
  sky130_fd_sc_hd__nand2_2 g24107(.A (n_1605), .B (n_770), .Y (n_967));
  sky130_fd_sc_hd__o2bb2ai_2 g69(.A1_N (n_981), .A2_N (n_1223), .B1
       (n_875), .B2 (n_1223), .Y (n_974));
  sky130_fd_sc_hd__inv_1 g72(.A (A[4]), .Y (n_875));
  sky130_fd_sc_hd__inv_4 g19(.A (n_43), .Y (n_981));
  sky130_fd_sc_hd__inv_2 g20(.A (A[3]), .Y (n_43));
  sky130_fd_sc_hd__nand2_1 g24112(.A (n_1168), .B (n_1014), .Y (n_987));
  sky130_fd_sc_hd__a21oi_2 g42(.A1 (n_966), .A2 (n_968), .B1 (n_1656),
       .Y (n_1010));
  sky130_fd_sc_hd__nor3_1 g33(.A (n_1014), .B (n_29), .C (n_1191), .Y
       (n_1015));
  sky130_fd_sc_hd__nand3_1 g146(.A (n_1025), .B (n_1028), .C (n_1654),
       .Y (n_1030));
  sky130_fd_sc_hd__nand3_1 g148(.A (n_1780), .B (n_1459), .C (n_886),
       .Y (n_1025));
  sky130_fd_sc_hd__and2_1 g147(.A (n_705), .B (n_1655), .X (n_1028));
  sky130_fd_sc_hd__a21boi_1 g297(.A1 (n_1241), .A2 (n_1061), .B1_N
       (n_164), .Y (n_1062));
  sky130_fd_sc_hd__nand2_1 g303(.A (n_204), .B (n_1883), .Y (n_1065));
  sky130_fd_sc_hd__nand3_2 g24143(.A (n_1067), .B (n_1142), .C (A[2]),
       .Y (n_1069));
  sky130_fd_sc_hd__nand2_4 g24144(.A (n_634), .B (n_29), .Y (n_1067));
  sky130_fd_sc_hd__xor2_1 g24171(.A (n_26), .B (A[3]), .X (n_1107));
  sky130_fd_sc_hd__nor2_1 g24174(.A (n_1738), .B (n_665), .Y (n_1115));
  sky130_fd_sc_hd__inv_2 g14(.A (n_544), .Y (n_1113));
  sky130_fd_sc_hd__o21ai_2 g25(.A1 (n_371), .A2 (n_418), .B1 (n_1170),
       .Y (n_1122));
  sky130_fd_sc_hd__nand2_2 g24179(.A (n_1123), .B (n_1410), .Y
       (n_1124));
  sky130_fd_sc_hd__nand2_2 g37(.A (n_1408), .B (n_26), .Y (n_1123));
  sky130_fd_sc_hd__clkinv_1 g362(.A (n_1129), .Y (n_1130));
  sky130_fd_sc_hd__nand2_1 g363(.A (n_1913), .B (n_1915), .Y (n_1129));
  sky130_fd_sc_hd__nand2_2 g24188(.A (n_1138), .B (n_178), .Y (n_1139));
  sky130_fd_sc_hd__nand2_2 g24189(.A (n_502), .B (n_1014), .Y (n_1138));
  sky130_fd_sc_hd__nand2_4 g31(.A (n_1660), .B (n_1144), .Y (n_1145));
  sky130_fd_sc_hd__nand2_4 g24190(.A (n_1246), .B (n_1249), .Y
       (n_1144));
  sky130_fd_sc_hd__nand2_2 g24192(.A (n_1603), .B (n_575), .Y (n_1142));
  sky130_fd_sc_hd__nand2_2 g24197(.A (n_1151), .B (n_1152), .Y
       (n_1153));
  sky130_fd_sc_hd__nand2_1 g87(.A (n_1168), .B (n_1506), .Y (n_1151));
  sky130_fd_sc_hd__nand2_1 g24198(.A (n_974), .B (n_1014), .Y (n_1152));
  sky130_fd_sc_hd__inv_2 g24201(.A (n_1164), .Y (n_1165));
  sky130_fd_sc_hd__inv_4 g65(.A (n_1163), .Y (n_1164));
  sky130_fd_sc_hd__inv_2 g24202(.A (n_1222), .Y (n_1163));
  sky130_fd_sc_hd__o21ai_1 g24204(.A1 (n_1163), .A2 (n_61), .B1
       (n_1167), .Y (n_1168));
  sky130_fd_sc_hd__nand2_1 g24205(.A (n_1223), .B (A[2]), .Y (n_1167));
  sky130_fd_sc_hd__nand2_1 g24206(.A (n_1164), .B (A[6]), .Y (n_1170));
  sky130_fd_sc_hd__inv_2 g64(.A (n_1164), .Y (n_1171));
  sky130_fd_sc_hd__nand2b_1 g24212(.A_N (n_1107), .B (n_1176), .Y
       (n_1177));
  sky130_fd_sc_hd__nand2_1 g24214(.A (n_1107), .B (n_634), .Y (n_1178));
  sky130_fd_sc_hd__buf_4 g38(.A (n_1190), .X (n_1191));
  sky130_fd_sc_hd__clkinv_4 g24222(.A (B[1]), .Y (n_1190));
  sky130_fd_sc_hd__nand2_2 g24224(.A (n_1881), .B (n_1191), .Y
       (n_1194));
  sky130_fd_sc_hd__nand2_1 g102(.A (n_271), .B (n_267), .Y (n_1200));
  sky130_fd_sc_hd__inv_1 g103(.A (n_665), .Y (n_1061));
  sky130_fd_sc_hd__nand2_2 g24233(.A (n_1630), .B (n_1210), .Y
       (n_1211));
  sky130_fd_sc_hd__inv_2 g134(.A (n_634), .Y (n_1176));
  sky130_fd_sc_hd__nand2_1 g130(.A (n_366), .B (n_634), .Y (n_1210));
  sky130_fd_sc_hd__clkinv_1 g124(.A (n_1928), .Y (n_1218));
  sky130_fd_sc_hd__inv_2 g24235(.A (n_1222), .Y (n_1223));
  sky130_fd_sc_hd__nand3_2 g24236(.A (i_op_sel[0]), .B (i_op_sel[2]),
       .C (i_op_sel[1]), .Y (n_1222));
  sky130_fd_sc_hd__o2bb2ai_1 g24237(.A1_N (n_836), .A2_N (n_101), .B1
       (A[5]), .B2 (n_1225), .Y (n_1226));
  sky130_fd_sc_hd__a22oi_1 g24238(.A1 (n_78), .A2 (n_1224), .B1 (n_78),
       .B2 (n_836), .Y (n_1225));
  sky130_fd_sc_hd__clkbuf_1 fopt24239(.A (op_sel[0]), .X (n_1224));
  sky130_fd_sc_hd__nand2_2 g24240(.A (n_78), .B (n_1224), .Y (n_1227));
  sky130_fd_sc_hd__a21oi_1 g511(.A1 (n_1581), .A2 (n_1231), .B1
       (n_1239), .Y (n_1240));
  sky130_fd_sc_hd__inv_1 g521(.A (n_1230), .Y (n_1231));
  sky130_fd_sc_hd__nand2_1 g522(.A (n_652), .B (n_159), .Y (n_1230));
  sky130_fd_sc_hd__nand3_1 g512(.A (n_1234), .B (n_1236), .C (n_1628),
       .Y (n_1239));
  sky130_fd_sc_hd__nand2b_1 g517(.A_N (n_1283), .B (n_1233), .Y
       (n_1234));
  sky130_fd_sc_hd__nand2_1 g523(.A (n_232), .B (n_1510), .Y (n_1233));
  sky130_fd_sc_hd__inv_1 g515(.A (n_1235), .Y (n_1236));
  sky130_fd_sc_hd__nor2_2 g516(.A (n_1283), .B (n_1884), .Y (n_1235));
  sky130_fd_sc_hd__nand3_1 g518(.A (n_232), .B (n_1884), .C (n_1510),
       .Y (n_1241));
  sky130_fd_sc_hd__nand2_4 g202(.A (n_1067), .B (n_1142), .Y (n_1246));
  sky130_fd_sc_hd__inv_2 g205(.A (A[2]), .Y (n_1249));
  sky130_fd_sc_hd__nand2_2 g10(.A (n_1251), .B (n_1252), .Y (n_1253));
  sky130_fd_sc_hd__inv_2 g24244(.A (n_1250), .Y (n_1251));
  sky130_fd_sc_hd__clkinv_2 g24245(.A (op_sel[1]), .Y (n_1250));
  sky130_fd_sc_hd__inv_2 g24246(.A (op_sel[2]), .Y (n_1252));
  sky130_fd_sc_hd__nand2_4 g24248(.A (n_1255), .B (n_1405), .Y
       (n_1257));
  sky130_fd_sc_hd__nand2_2 g24249(.A (n_1611), .B (n_827), .Y (n_1255));
  sky130_fd_sc_hd__nand2_2 g45(.A (n_1271), .B (n_1272), .Y (n_1273));
  sky130_fd_sc_hd__o21ai_1 g46(.A1 (n_371), .A2 (n_1171), .B1 (n_505),
       .Y (n_1271));
  sky130_fd_sc_hd__buf_6 fopt51(.A (B[0]), .X (n_1272));
  sky130_fd_sc_hd__inv_4 fopt24253(.A (n_1272), .Y (n_1014));
  sky130_fd_sc_hd__nand3_2 g24257(.A (n_1065), .B (n_724), .C (n_725),
       .Y (n_1282));
  sky130_fd_sc_hd__inv_4 g24258(.A (n_1283), .Y (n_607));
  sky130_fd_sc_hd__nand2_4 g24259(.A (n_544), .B (n_159), .Y (n_1283));
  sky130_fd_sc_hd__nand3_2 g24298(.A (n_966), .B (n_254), .C (n_968),
       .Y (n_1355));
  sky130_fd_sc_hd__nor2_2 g24299(.A (n_273), .B (n_240), .Y (n_1356));
  sky130_fd_sc_hd__nand2_2 g24328(.A (n_1602), .B (n_21), .Y (n_1405));
  sky130_fd_sc_hd__clkinv_2 g24332(.A (n_1602), .Y (n_1408));
  sky130_fd_sc_hd__nand2_1 g24333(.A (n_1602), .B (B[3]), .Y (n_1410));
  sky130_fd_sc_hd__dlymetal6s2s_1 g24334(.A (n_1602), .X (n_1411));
  sky130_fd_sc_hd__inv_2 g24336(.A (n_1548), .Y (n_1413));
  sky130_fd_sc_hd__nand3_1 g24345(.A (n_1925), .B (n_1904), .C
       (n_1930), .Y (n_1423));
  sky130_fd_sc_hd__nand2_4 g24375(.A (n_1139), .B (n_1883), .Y
       (n_1449));
  sky130_fd_sc_hd__nand2_4 g24377(.A (n_1153), .B (n_71), .Y (n_1451));
  sky130_fd_sc_hd__nor2b_1 g24381(.A (n_1653), .B_N (n_1688), .Y
       (n_1459));
  sky130_fd_sc_hd__nand3_1 g24383(.A (n_1257), .B (A[4]), .C (n_1930),
       .Y (n_1460));
  sky130_fd_sc_hd__inv_2 g24384(.A (n_1461), .Y (n_1462));
  sky130_fd_sc_hd__nand2_4 g24385(.A (n_1257), .B (A[4]), .Y (n_1461));
  sky130_fd_sc_hd__nand3_1 g1827(.A (n_1467), .B (n_1474), .C (n_1910),
       .Y (n_1477));
  sky130_fd_sc_hd__nand2_1 g1830(.A (n_1909), .B (n_1466), .Y (n_1467));
  sky130_fd_sc_hd__nand3_2 g1834(.A (n_926), .B (n_927), .C (n_929), .Y
       (n_1463));
  sky130_fd_sc_hd__nor2_1 g1840(.A (n_968), .B (n_965), .Y (n_1466));
  sky130_fd_sc_hd__nor2_2 g1828(.A (n_1469), .B (n_1473), .Y (n_1474));
  sky130_fd_sc_hd__a21oi_1 g1835(.A1 (n_1194), .A2 (n_163), .B1
       (n_1468), .Y (n_1469));
  sky130_fd_sc_hd__nand2_1 g1841(.A (n_607), .B (n_575), .Y (n_1468));
  sky130_fd_sc_hd__nand3_2 g1832(.A (n_1470), .B (n_1471), .C (n_1472),
       .Y (n_1473));
  sky130_fd_sc_hd__nand2_1 g1838(.A (n_1282), .B (n_607), .Y (n_1470));
  sky130_fd_sc_hd__a21oi_2 g1833(.A1 (n_151), .A2 (A[6]), .B1 (n_194),
       .Y (n_1471));
  sky130_fd_sc_hd__nand2_1 g1839(.A (n_1115), .B (n_216), .Y (n_1472));
  sky130_fd_sc_hd__nor2b_1 g1842(.A (n_965), .B_N (n_968), .Y (n_1475));
  sky130_fd_sc_hd__nand2_2 g1837(.A (n_1194), .B (n_163), .Y (n_1478));
  sky130_fd_sc_hd__inv_2 g24414(.A (n_1014), .Y (n_1506));
  sky130_fd_sc_hd__nand2_1 g24415(.A (n_1508), .B (n_1509), .Y
       (n_1510));
  sky130_fd_sc_hd__nor2b_1 g32(.A (n_29), .B_N (n_1507), .Y (n_1508));
  sky130_fd_sc_hd__nor2_1 g24416(.A (n_32), .B (n_1272), .Y (n_1507));
  sky130_fd_sc_hd__nand2_2 g24417(.A (n_667), .B (n_123), .Y (n_1509));
  sky130_fd_sc_hd__inv_2 g24418(.A (n_29), .Y (n_575));
  sky130_fd_sc_hd__xnor2_1 g24419(.A (n_1512), .B (n_1515), .Y
       (n_1516));
  sky130_fd_sc_hd__inv_2 g49(.A (n_1660), .Y (n_1512));
  sky130_fd_sc_hd__o22ai_1 g47(.A1 (A[2]), .A2 (n_1246), .B1 (n_1249),
       .B2 (n_1514), .Y (n_1515));
  sky130_fd_sc_hd__inv_1 g48(.A (n_1246), .Y (n_1514));
  sky130_fd_sc_hd__nand2_1 g41(.A (n_1924), .B (n_1527), .Y (n_1528));
  sky130_fd_sc_hd__a21oi_2 g24430(.A1 (n_218), .A2 (n_173), .B1
       (n_224), .Y (n_1527));
  sky130_fd_sc_hd__inv_2 g24447(.A (n_1069), .Y (n_1548));
  sky130_fd_sc_hd__inv_1 g24449(.A (n_1548), .Y (n_1549));
  sky130_fd_sc_hd__nand2_1 g22(.A (n_1579), .B (n_1580), .Y (n_1581));
  sky130_fd_sc_hd__nand2_1 g24(.A (n_216), .B (n_1578), .Y (n_1579));
  sky130_fd_sc_hd__inv_1 g24475(.A (n_1191), .Y (n_1578));
  sky130_fd_sc_hd__nand2_1 g23(.A (n_1153), .B (n_1191), .Y (n_1580));
  sky130_fd_sc_hd__inv_2 g24490(.A (n_1601), .Y (n_1602));
  sky130_fd_sc_hd__inv_2 g24491(.A (n_1600), .Y (n_1601));
  sky130_fd_sc_hd__nand3_2 g24492(.A (n_782), .B (n_783), .C
       (i_op_sel[0]), .Y (n_1600));
  sky130_fd_sc_hd__inv_2 g24493(.A (n_1600), .Y (n_1603));
  sky130_fd_sc_hd__nand2_1 g24494(.A (n_450), .B (n_1873), .Y (n_1605));
  sky130_fd_sc_hd__nand2_1 g24498(.A (n_1873), .B (n_836), .Y (n_1608));
  sky130_fd_sc_hd__inv_2 g24499(.A (n_1873), .Y (n_1609));
  sky130_fd_sc_hd__inv_2 g24501(.A (n_1873), .Y (n_1611));
  sky130_fd_sc_hd__nand3_2 g1(.A (n_1612), .B (n_1613), .C (n_1614), .Y
       (n_1615));
  sky130_fd_sc_hd__nand2_1 g24504(.A (n_216), .B (n_71), .Y (n_1612));
  sky130_fd_sc_hd__nand2_1 g24505(.A (n_1153), .B (n_1883), .Y
       (n_1613));
  sky130_fd_sc_hd__nand2_1 g24506(.A (n_1739), .B (n_1139), .Y
       (n_1614));
  sky130_fd_sc_hd__nand3_1 g24511(.A (n_1621), .B (n_1620), .C
       (n_1622), .Y (n_1623));
  sky130_fd_sc_hd__nand2_1 g78(.A (n_1516), .B (n_1930), .Y (n_1620));
  sky130_fd_sc_hd__nand2_1 g77(.A (n_1615), .B (n_1061), .Y (n_1621));
  sky130_fd_sc_hd__a21oi_1 g24512(.A1 (n_1478), .A2 (n_218), .B1
       (n_206), .Y (n_1622));
  sky130_fd_sc_hd__inv_2 g24513(.A (n_1873), .Y (n_1624));
  sky130_fd_sc_hd__nand2b_1 g2(.A_N (n_1462), .B (n_1906), .Y (n_1627));
  sky130_fd_sc_hd__o2111a_1 g24514(.A1 (A[4]), .A2 (n_112), .B1 (n_95),
       .C1 (n_108), .D1 (n_104), .X (n_1628));
  sky130_fd_sc_hd__nand4b_1 g24515(.A_N (B[0]), .B (n_401), .C
       (i_op_sel[0]), .D (n_52), .Y (n_1629));
  sky130_fd_sc_hd__nand2b_1 g24516(.A_N (n_366), .B (n_1176), .Y
       (n_1630));
  sky130_fd_sc_hd__nand2_1 g24530(.A (n_1509), .B (n_1015), .Y
       (n_1643));
  sky130_fd_sc_hd__nand2_1 g24531(.A (n_1122), .B (n_1932), .Y
       (n_1645));
  sky130_fd_sc_hd__buf_1 g82(.A (n_1652), .X (n_1653));
  sky130_fd_sc_hd__nand2_2 g83(.A (n_1931), .B (n_1651), .Y (n_1652));
  sky130_fd_sc_hd__nand2_1 g84(.A (n_481), .B (n_1873), .Y (n_1651));
  sky130_fd_sc_hd__nand4b_1 g24536(.A_N (n_1653), .B (n_966), .C
       (n_968), .D (n_1688), .Y (n_1654));
  sky130_fd_sc_hd__nand2b_1 g24537(.A_N (n_1652), .B (n_1879), .Y
       (n_1655));
  sky130_fd_sc_hd__nand3b_1 g79(.A_N (n_1652), .B (n_1880), .C
       (n_1930), .Y (n_1656));
  sky130_fd_sc_hd__nand2_2 g80(.A (n_1652), .B (n_1930), .Y (n_1657));
  sky130_fd_sc_hd__nand2_4 g91(.A (n_1659), .B (n_181), .Y (n_1660));
  sky130_fd_sc_hd__o21ai_2 g93(.A1 (A[1]), .A2 (n_153), .B1 (n_1658),
       .Y (n_1659));
  sky130_fd_sc_hd__o21ai_2 g24538(.A1 (n_1190), .A2 (n_672), .B1
       (n_797), .Y (n_1658));
  sky130_fd_sc_hd__xnor2_1 g92(.A (n_1658), .B (A[1]), .Y (n_1661));
  sky130_fd_sc_hd__nand2_1 g509(.A (n_1668), .B (n_886), .Y (n_1669));
  sky130_fd_sc_hd__nand2_2 g24539(.A (n_1666), .B (n_1779), .Y
       (n_1668));
  sky130_fd_sc_hd__nand2_4 g24540(.A (n_1663), .B (n_1665), .Y
       (n_1666));
  sky130_fd_sc_hd__nand2_4 g24541(.A (n_1145), .B (n_1413), .Y
       (n_1663));
  sky130_fd_sc_hd__inv_4 g528(.A (n_1664), .Y (n_1665));
  sky130_fd_sc_hd__nand2_2 g529(.A (n_1177), .B (n_1178), .Y (n_1664));
  sky130_fd_sc_hd__nand2_1 g508(.A (n_1672), .B (n_1673), .Y (n_1674));
  sky130_fd_sc_hd__o21ai_1 g510(.A1 (n_1423), .A2 (n_1670), .B1
       (n_1671), .Y (n_1672));
  sky130_fd_sc_hd__inv_1 g24542(.A (n_1666), .Y (n_1670));
  sky130_fd_sc_hd__inv_1 g530(.A (n_717), .Y (n_1671));
  sky130_fd_sc_hd__nand3_1 g514(.A (n_1423), .B (n_1666), .C (n_1779),
       .Y (n_1673));
  sky130_fd_sc_hd__nand2_2 g24545(.A (n_1907), .B (n_1781), .Y
       (n_1683));
  sky130_fd_sc_hd__nand3_1 g24546(.A (n_1549), .B (n_1145), .C
       (n_1665), .Y (n_1684));
  sky130_fd_sc_hd__buf_2 fopt24548(.A (n_1740), .X (n_1686));
  sky130_fd_sc_hd__buf_2 fopt24550(.A (n_1690), .X (n_1688));
  sky130_fd_sc_hd__clkinv_2 fopt24551(.A (n_669), .Y (n_1690));
  sky130_fd_sc_hd__nand3_2 g24595(.A (n_1731), .B (n_1355), .C
       (n_1356), .Y (n_1732));
  sky130_fd_sc_hd__nand2_2 g24596(.A (n_1921), .B (n_607), .Y (n_1731));
  sky130_fd_sc_hd__nand2_4 g24599(.A (n_1737), .B (n_1739), .Y
       (n_1740));
  sky130_fd_sc_hd__nand2_2 g24600(.A (n_1273), .B (n_183), .Y (n_1737));
  sky130_fd_sc_hd__inv_4 g21(.A (n_1738), .Y (n_1739));
  sky130_fd_sc_hd__nand2b_2 g24601(.A_N (B[2]), .B (n_1190), .Y
       (n_1738));
  sky130_fd_sc_hd__nand3_2 g43(.A (n_1892), .B (n_1742), .C (n_1743),
       .Y (n_1744));
  sky130_fd_sc_hd__inv_1 g24603(.A (n_1200), .Y (n_1742));
  sky130_fd_sc_hd__nand2_1 g24604(.A (n_1615), .B (n_607), .Y (n_1743));
  sky130_fd_sc_hd__nand2_1 g18(.A (n_1778), .B (n_1779), .Y (n_1780));
  sky130_fd_sc_hd__nand2_1 g24640(.A (n_1663), .B (n_1665), .Y
       (n_1778));
  sky130_fd_sc_hd__clkbuf_2 g24641(.A (n_1925), .X (n_1779));
  sky130_fd_sc_hd__inv_1 g24642(.A (n_1665), .Y (n_1781));
  sky130_fd_sc_hd__nand2_4 g24646(.A (n_1113), .B (n_159), .Y (n_665));
  sky130_fd_sc_hd__nand3_2 g24652(.A (n_1793), .B (n_1794), .C
       (n_1795), .Y (n_1796));
  sky130_fd_sc_hd__clkinv_2 g24653(.A (n_1732), .Y (n_1793));
  sky130_fd_sc_hd__nand2_1 g24654(.A (n_1010), .B (n_1669), .Y
       (n_1794));
  sky130_fd_sc_hd__nand3_1 g44(.A (n_1780), .B (n_886), .C (n_254), .Y
       (n_1795));
  sky130_fd_sc_hd__xnor2_2 g24719(.A (n_959), .B (n_1624), .Y (n_1862));
  sky130_fd_sc_hd__buf_6 g24726(.A (B[6]), .X (n_1872));
  sky130_fd_sc_hd__inv_4 g24727(.A (n_1603), .Y (n_1873));
  sky130_fd_sc_hd__and3_2 g24728(.A (n_1878), .B (n_1688), .C (A[6]),
       .X (n_1879));
  sky130_fd_sc_hd__nand2_1 g24729(.A (n_1876), .B (n_1877), .Y
       (n_1878));
  sky130_fd_sc_hd__nand2_1 g24730(.A (n_1874), .B (n_1875), .Y
       (n_1876));
  sky130_fd_sc_hd__inv_2 g3(.A (n_1872), .Y (n_1874));
  sky130_fd_sc_hd__inv_1 g4(.A (n_1873), .Y (n_1875));
  sky130_fd_sc_hd__nand2_1 g5(.A (n_1872), .B (n_1873), .Y (n_1877));
  sky130_fd_sc_hd__nand2_1 g24731(.A (n_1878), .B (A[6]), .Y (n_1880));
  sky130_fd_sc_hd__nand2_2 g24733(.A (n_1881), .B (n_1883), .Y
       (n_1884));
  sky130_fd_sc_hd__nand2_2 g24734(.A (n_184), .B (n_987), .Y (n_1881));
  sky130_fd_sc_hd__nor2_2 g26(.A (B[2]), .B (n_1191), .Y (n_1883));
  sky130_fd_sc_hd__buf_1 g24736(.A (n_23), .X (n_1887));
  sky130_fd_sc_hd__nand3_2 g24737(.A (n_1888), .B (n_1889), .C
       (n_1930), .Y (n_1892));
  sky130_fd_sc_hd__nand2_2 g24738(.A (n_1130), .B (n_1218), .Y
       (n_1888));
  sky130_fd_sc_hd__nand2_1 g50(.A (n_1929), .B (n_1627), .Y (n_1889));
  sky130_fd_sc_hd__buf_2 g24743(.A (n_1449), .X (n_1894));
  sky130_fd_sc_hd__inv_2 g24750(.A (n_1862), .Y (n_1904));
  sky130_fd_sc_hd__inv_4 g24752(.A (n_1211), .Y (n_1906));
  sky130_fd_sc_hd__nand2_2 g523_dup24753(.A (n_1145), .B (n_1413), .Y
       (n_1907));
  sky130_fd_sc_hd__nand2_1 g24754(.A (n_1463), .B (n_1908), .Y
       (n_1909));
  sky130_fd_sc_hd__nand4_2 g24755(.A (n_1907), .B (n_1904), .C
       (n_1665), .D (n_1906), .Y (n_1908));
  sky130_fd_sc_hd__nand3_1 g24756(.A (n_1463), .B (n_1475), .C
       (n_1908), .Y (n_1910));
  sky130_fd_sc_hd__nand3_2 g155(.A (n_1512), .B (n_1549), .C (n_1925),
       .Y (n_1913));
  sky130_fd_sc_hd__nand2b_1 g158(.A_N (n_1257), .B (n_875), .Y
       (n_1915));
  sky130_fd_sc_hd__nand2_2 g157(.A (n_1925), .B (n_1664), .Y (n_1916));
  sky130_fd_sc_hd__clkinv_2 g24761(.A (n_1918), .Y (n_1919));
  sky130_fd_sc_hd__nand2_2 g24762(.A (n_1643), .B (n_1645), .Y
       (n_1918));
  sky130_fd_sc_hd__nand4_4 g24763(.A (n_1919), .B (n_1449), .C
       (n_1740), .D (n_1451), .Y (n_1921));
  sky130_fd_sc_hd__nand2_1 g24765(.A (n_1922), .B (n_1061), .Y
       (n_1924));
  sky130_fd_sc_hd__nand4_1 g24766(.A (n_1686), .B (n_1894), .C
       (n_1451), .D (n_1919), .Y (n_1922));
  sky130_fd_sc_hd__nand2_4 g24767(.A (n_1124), .B (n_981), .Y (n_1925));
  sky130_fd_sc_hd__nand3_2 g24768(.A (n_1927), .B (n_1916), .C
       (n_1906), .Y (n_1928));
  sky130_fd_sc_hd__nand2_2 g24769(.A (n_1925), .B (n_1926), .Y
       (n_1927));
  sky130_fd_sc_hd__inv_1 g24770(.A (n_1144), .Y (n_1926));
  sky130_fd_sc_hd__nand4_1 g24771(.A (n_1913), .B (n_1927), .C
       (n_1915), .D (n_1916), .Y (n_1929));
  sky130_fd_sc_hd__nor2_2 g24772(.A (n_50), .B (n_23), .Y (n_1930));
  sky130_fd_sc_hd__nand2b_2 g24773(.A_N (n_481), .B (n_1609), .Y
       (n_1931));
  sky130_fd_sc_hd__nor3b_1 g24774(.A (n_29), .B (n_1191), .C_N
       (n_1014), .Y (n_1932));
endmodule

module synth_wrapper(clk, rst_n, A, B, op_sel, result, carry);
  input clk, rst_n;
  input [7:0] A, B;
  input [2:0] op_sel;
  output [7:0] result;
  output carry;
  wire clk, rst_n;
  wire [7:0] A, B;
  wire [2:0] op_sel;
  wire [7:0] result;
  wire carry;
  wire [7:0] A_reg;
  wire [7:0] B_reg;
  wire [2:0] op_sel_reg;
  wire carry_reg_84, \result_reg[0]_60 , \result_reg[1]_61 ,
       \result_reg[2]_62 , \result_reg[3]_63 , \result_reg[4]_64 ,
       \result_reg[5]_65 , \result_reg[6]_66 ;
  wire \result_reg[7]_67 ;
  alu_8bit dutty(.i_clk (clk), .i_rstn (rst_n), .i_a (A_reg), .i_b
       (B_reg), .i_op_sel (op_sel_reg), .o_result ({\result_reg[7]_67 ,
       \result_reg[6]_66 , \result_reg[5]_65 , \result_reg[4]_64 ,
       \result_reg[3]_63 , \result_reg[2]_62 , \result_reg[1]_61 ,
       \result_reg[0]_60 }), .o_carry (carry_reg_84));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[7] (.RESET_B (rst_n), .CLK
       (clk), .D (\result_reg[7]_67 ), .Q (result[7]));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[6] (.RESET_B (rst_n), .CLK
       (clk), .D (\result_reg[6]_66 ), .Q (result[6]));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[4] (.RESET_B (rst_n), .CLK
       (clk), .D (\result_reg[4]_64 ), .Q (result[4]));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[0] (.RESET_B (rst_n), .CLK
       (clk), .D (\result_reg[0]_60 ), .Q (result[0]));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[2] (.RESET_B (rst_n), .CLK
       (clk), .D (\result_reg[2]_62 ), .Q (result[2]));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[3] (.RESET_B (rst_n), .CLK
       (clk), .D (\result_reg[3]_63 ), .Q (result[3]));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[5] (.RESET_B (rst_n), .CLK
       (clk), .D (\result_reg[5]_65 ), .Q (result[5]));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[1] (.RESET_B (rst_n), .CLK
       (clk), .D (\result_reg[1]_61 ), .Q (result[1]));
  sky130_fd_sc_hd__dfrtp_1 carry_reg(.RESET_B (rst_n), .CLK (clk), .D
       (carry_reg_84), .Q (carry));
  sky130_fd_sc_hd__dfrtp_1 \A_reg_reg[6] (.RESET_B (rst_n), .CLK (clk),
       .D (A[6]), .Q (A_reg[6]));
  sky130_fd_sc_hd__dfrtp_1 \A_reg_reg[7] (.RESET_B (rst_n), .CLK (clk),
       .D (A[7]), .Q (A_reg[7]));
  sky130_fd_sc_hd__dfrtp_1 \B_reg_reg[5] (.RESET_B (rst_n), .CLK (clk),
       .D (B[5]), .Q (B_reg[5]));
  sky130_fd_sc_hd__dfrtp_1 \A_reg_reg[4] (.RESET_B (rst_n), .CLK (clk),
       .D (A[4]), .Q (A_reg[4]));
  sky130_fd_sc_hd__dfrtp_1 \A_reg_reg[1] (.RESET_B (rst_n), .CLK (clk),
       .D (A[1]), .Q (A_reg[1]));
  sky130_fd_sc_hd__dfrtp_1 \A_reg_reg[5] (.RESET_B (rst_n), .CLK (clk),
       .D (A[5]), .Q (A_reg[5]));
  sky130_fd_sc_hd__dfrtp_1 \A_reg_reg[2] (.RESET_B (rst_n), .CLK (clk),
       .D (A[2]), .Q (A_reg[2]));
  sky130_fd_sc_hd__dfrtp_2 \op_sel_reg_reg[0] (.RESET_B (rst_n), .CLK
       (clk), .D (op_sel[0]), .Q (op_sel_reg[0]));
  sky130_fd_sc_hd__dfrtp_1 \B_reg_reg[4] (.RESET_B (rst_n), .CLK (clk),
       .D (B[4]), .Q (B_reg[4]));
  sky130_fd_sc_hd__dfrtp_1 \B_reg_reg[0] (.RESET_B (rst_n), .CLK (clk),
       .D (B[0]), .Q (B_reg[0]));
  sky130_fd_sc_hd__dfrtp_1 \B_reg_reg[2] (.RESET_B (rst_n), .CLK (clk),
       .D (B[2]), .Q (B_reg[2]));
  sky130_fd_sc_hd__dfrtp_1 \B_reg_reg[3] (.RESET_B (rst_n), .CLK (clk),
       .D (B[3]), .Q (B_reg[3]));
  sky130_fd_sc_hd__dfrtp_2 \op_sel_reg_reg[1] (.RESET_B (rst_n), .CLK
       (clk), .D (op_sel[1]), .Q (op_sel_reg[1]));
  sky130_fd_sc_hd__dfrtp_1 \B_reg_reg[1] (.RESET_B (rst_n), .CLK (clk),
       .D (B[1]), .Q (B_reg[1]));
  sky130_fd_sc_hd__dfrtp_1 \B_reg_reg[6] (.RESET_B (rst_n), .CLK (clk),
       .D (B[6]), .Q (B_reg[6]));
  sky130_fd_sc_hd__dfrtp_1 \B_reg_reg[7] (.RESET_B (rst_n), .CLK (clk),
       .D (B[7]), .Q (B_reg[7]));
  sky130_fd_sc_hd__dfrtp_1 \A_reg_reg[3] (.RESET_B (rst_n), .CLK (clk),
       .D (A[3]), .Q (A_reg[3]));
  sky130_fd_sc_hd__dfrtp_2 \op_sel_reg_reg[2] (.RESET_B (rst_n), .CLK
       (clk), .D (op_sel[2]), .Q (op_sel_reg[2]));
  sky130_fd_sc_hd__dfrtp_1 \A_reg_reg[0] (.RESET_B (rst_n), .CLK (clk),
       .D (A[0]), .Q (A_reg[0]));
endmodule

