
// Generated by Cadence Genus(TM) Synthesis Solution GENUS15.20 - 15.20-p004_1
// Generated on: May 24 2025 16:37:22

// Verification Directory fv/synth_wrapper 

module d_flipflop_27(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_1 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_19(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_1 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_20(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_1 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_21(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_1 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_22(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_1 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_23(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_1 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_24(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_1 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_25(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_1 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_26(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_1 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module register_8bit_2(clk, rstn, d, q);
  input clk, rstn;
  input [7:0] d;
  output [7:0] q;
  wire clk, rstn;
  wire [7:0] d;
  wire [7:0] q;
  d_flipflop_19 bit0(.clk (clk), .rstn (rstn), .d (d[0]), .q (q[0]));
  d_flipflop_20 bit1(.clk (clk), .rstn (rstn), .d (d[1]), .q (q[1]));
  d_flipflop_21 bit2(.clk (clk), .rstn (rstn), .d (d[2]), .q (q[2]));
  d_flipflop_22 bit3(.clk (clk), .rstn (rstn), .d (d[3]), .q (q[3]));
  d_flipflop_23 bit4(.clk (clk), .rstn (rstn), .d (d[4]), .q (q[4]));
  d_flipflop_24 bit5(.clk (clk), .rstn (rstn), .d (d[5]), .q (q[5]));
  d_flipflop_25 bit6(.clk (clk), .rstn (rstn), .d (d[6]), .q (q[6]));
  d_flipflop_26 bit7(.clk (clk), .rstn (rstn), .d (d[7]), .q (q[7]));
endmodule

module d_flipflop(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_1 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_1(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_2 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_2(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_1 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_3(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_1 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_4(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_2 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_5(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_1 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_6(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_2 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_7(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_2 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module register_8bit(clk, rstn, d, q);
  input clk, rstn;
  input [7:0] d;
  output [7:0] q;
  wire clk, rstn;
  wire [7:0] d;
  wire [7:0] q;
  d_flipflop bit0(clk, rstn, d[0], q[0]);
  d_flipflop_1 bit1(clk, rstn, d[1], q[1]);
  d_flipflop_2 bit2(clk, rstn, d[2], q[2]);
  d_flipflop_3 bit3(clk, rstn, d[3], q[3]);
  d_flipflop_4 bit4(clk, rstn, d[4], q[4]);
  d_flipflop_5 bit5(clk, rstn, d[5], q[5]);
  d_flipflop_6 bit6(clk, rstn, d[6], q[6]);
  d_flipflop_7 bit7(clk, rstn, d[7], q[7]);
endmodule

module d_flipflop_11(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_1 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_12(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_1 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_13(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_2 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_14(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_1 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_15(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_1 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_16(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_1 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_17(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_1 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_18(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_1 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module register_8bit_1(clk, rstn, d, q);
  input clk, rstn;
  input [7:0] d;
  output [7:0] q;
  wire clk, rstn;
  wire [7:0] d;
  wire [7:0] q;
  d_flipflop_11 bit0(.clk (clk), .rstn (rstn), .d (d[0]), .q (q[0]));
  d_flipflop_12 bit1(.clk (clk), .rstn (rstn), .d (d[1]), .q (q[1]));
  d_flipflop_13 bit2(.clk (clk), .rstn (rstn), .d (d[2]), .q (q[2]));
  d_flipflop_14 bit3(.clk (clk), .rstn (rstn), .d (d[3]), .q (q[3]));
  d_flipflop_15 bit4(.clk (clk), .rstn (rstn), .d (d[4]), .q (q[4]));
  d_flipflop_16 bit5(.clk (clk), .rstn (rstn), .d (d[5]), .q (q[5]));
  d_flipflop_17 bit6(.clk (clk), .rstn (rstn), .d (d[6]), .q (q[6]));
  d_flipflop_18 bit7(.clk (clk), .rstn (rstn), .d (d[7]), .q (q[7]));
endmodule

module d_flipflop_8(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_1 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_9(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_1 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module d_flipflop_10(clk, rstn, d, q);
  input clk, rstn, d;
  output q;
  wire clk, rstn, d;
  wire q;
  sky130_fd_sc_hd__dfrtp_1 q_reg(.RESET_B (rstn), .CLK (clk), .D (d),
       .Q (q));
endmodule

module register_3bit(clk, rstn, d, q);
  input clk, rstn;
  input [2:0] d;
  output [2:0] q;
  wire clk, rstn;
  wire [2:0] d;
  wire [2:0] q;
  d_flipflop_8 bit0(clk, rstn, d[0], q[0]);
  d_flipflop_9 bit1(clk, rstn, d[1], q[1]);
  d_flipflop_10 bit2(clk, rstn, d[2], q[2]);
endmodule

module alu_8bit(i_clk, i_rstn, i_a, i_b, i_op_sel, o_result, o_carry);
  input i_clk, i_rstn;
  input [7:0] i_a, i_b;
  input [2:0] i_op_sel;
  output [7:0] o_result;
  output o_carry;
  wire i_clk, i_rstn;
  wire [7:0] i_a, i_b;
  wire [2:0] i_op_sel;
  wire [7:0] o_result;
  wire o_carry;
  wire [7:0] result_d;
  wire [7:0] A;
  wire [7:0] B;
  wire [2:0] op_sel;
  wire carry_d, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_101, n_102, n_103;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_133, n_134, n_135;
  wire n_136, n_137, n_138, n_139, n_140, n_141, n_142, n_143;
  wire n_144, n_145, n_146, n_147, n_148, n_149, n_150, n_151;
  wire n_152, n_153, n_154, n_155, n_156, n_157, n_158, n_159;
  wire n_160, n_161, n_162, n_163, n_164, n_165, n_166, n_167;
  wire n_168, n_169, n_170, n_171, n_172, n_173, n_174, n_175;
  wire n_176, n_177, n_178, n_179, n_180, n_181, n_182, n_183;
  wire n_184, n_185, n_186, n_187, n_188, n_189, n_190, n_191;
  wire n_192, n_193, n_194, n_195, n_196, n_197, n_198, n_199;
  wire n_200, n_201, n_202, n_203, n_204, n_205, n_206, n_207;
  wire n_208, n_209, n_210, n_211, n_212, n_213, n_214, n_215;
  wire n_216, n_217, n_218, n_219, n_220, n_221, n_222, n_223;
  wire n_224, n_225, n_226, n_227, n_228, n_229, n_230, n_231;
  wire n_232, n_233, n_234, n_235, n_236, n_237, n_238, n_239;
  wire n_240, n_241, n_242, n_243, n_244, n_245, n_246, n_247;
  wire n_248, n_249, n_250, n_251, n_252, n_253, n_254, n_255;
  wire n_256, n_257, n_258, n_259, n_260, n_261, n_262, n_263;
  wire n_264, n_265, n_266, n_267, n_268, n_269, n_270, n_271;
  wire n_272, n_273, n_274, n_275, n_276, n_277, n_278, n_279;
  wire n_280, n_281, n_282, n_283, n_284, n_285, n_286, n_287;
  wire n_288, n_289, n_290, n_291, n_292, n_293, n_294, n_295;
  wire n_296, n_297, n_298, n_299, n_300, n_301, n_302, n_303;
  wire n_304, n_305, n_306, n_307, n_308, n_309;
  d_flipflop_27 Cout_buff(i_clk, i_rstn, carry_d, o_carry);
  register_8bit_2 S_buff(i_clk, i_rstn, result_d, o_result);
  register_8bit fetch_A(i_clk, i_rstn, i_a, A);
  register_8bit_1 fetch_B(i_clk, i_rstn, i_b, B);
  register_3bit fetch_op(i_clk, i_rstn, i_op_sel, op_sel);
  sky130_fd_sc_hd__o211ai_1 g23291(.A1 (n_277), .A2 (n_305), .B1
       (n_309), .C1 (n_293), .Y (result_d[7]));
  sky130_fd_sc_hd__o2bb2ai_1 g23292(.A1_N (n_80), .A2_N (n_161), .B1
       (n_249), .B2 (n_308), .Y (carry_d));
  sky130_fd_sc_hd__o21ai_1 g23293(.A1 (n_75), .A2 (n_307), .B1 (n_289),
       .Y (result_d[4]));
  sky130_fd_sc_hd__nand3_1 g23294(.A (n_301), .B (n_262), .C (n_254),
       .Y (n_309));
  sky130_fd_sc_hd__nand3_1 g23295(.A (n_304), .B (n_281), .C (n_266),
       .Y (result_d[3]));
  sky130_fd_sc_hd__a21oi_2 g23296(.A1 (n_301), .A2 (n_262), .B1
       (n_283), .Y (n_308));
  sky130_fd_sc_hd__nand2_1 g23297(.A (n_306), .B (n_288), .Y
       (result_d[5]));
  sky130_fd_sc_hd__xnor2_1 g23298(.A (n_236), .B (n_301), .Y (n_307));
  sky130_fd_sc_hd__nand2_1 g23299(.A (n_300), .B (n_76), .Y (n_306));
  sky130_fd_sc_hd__nor2_1 g23300(.A (n_261), .B (n_302), .Y (n_305));
  sky130_fd_sc_hd__nand2_1 g23301(.A (n_303), .B (n_162), .Y (n_304));
  sky130_fd_sc_hd__nand3_1 g23302(.A (n_299), .B (n_282), .C (n_298),
       .Y (result_d[6]));
  sky130_fd_sc_hd__nand3_1 g23303(.A (n_0), .B (n_292), .C (n_47), .Y
       (n_303));
  sky130_fd_sc_hd__inv_2 g23304(.A (n_301), .Y (n_302));
  sky130_fd_sc_hd__o21ai_1 g23305(.A1 (n_196), .A2 (n_296), .B1
       (n_297), .Y (n_300));
  sky130_fd_sc_hd__nand2_4 g23306(.A (n_291), .B (n_40), .Y (n_301));
  sky130_fd_sc_hd__o211ai_1 g23307(.A1 (n_170), .A2 (n_259), .B1
       (n_294), .C1 (n_265), .Y (result_d[2]));
  sky130_fd_sc_hd__nand2_1 g23308(.A (n_295), .B (n_247), .Y (n_299));
  sky130_fd_sc_hd__nand4_1 g23309(.A (n_290), .B (n_287), .C (n_76), .D
       (n_199), .Y (n_298));
  sky130_fd_sc_hd__nand2_1 g23310(.A (n_296), .B (n_6), .Y (n_297));
  sky130_fd_sc_hd__nand2_1 g23311(.A (n_290), .B (n_287), .Y (n_295));
  sky130_fd_sc_hd__nand4_2 g23312(.A (n_276), .B (n_251), .C (n_5), .D
       (n_4), .Y (n_296));
  sky130_fd_sc_hd__a21oi_1 g23313(.A1 (n_280), .A2 (n_76), .B1 (n_206),
       .Y (n_294));
  sky130_fd_sc_hd__o211a_1 g23314(.A1 (n_189), .A2 (n_268), .B1
       (n_285), .C1 (n_284), .X (n_293));
  sky130_fd_sc_hd__nand2_1 g23315(.A (n_12), .B (n_17), .Y (n_292));
  sky130_fd_sc_hd__nand2_2 g23317(.A (n_17), .B (n_286), .Y (n_291));
  sky130_fd_sc_hd__a21oi_1 g23318(.A1 (n_245), .A2 (n_220), .B1
       (n_279), .Y (n_289));
  sky130_fd_sc_hd__o21ai_1 g23319(.A1 (n_170), .A2 (n_272), .B1 (n_10),
       .Y (result_d[1]));
  sky130_fd_sc_hd__nand3_2 g23320(.A (n_255), .B (n_13), .C (n_196), .Y
       (n_290));
  sky130_fd_sc_hd__a21oi_2 g23321(.A1 (n_258), .A2 (n_188), .B1
       (n_278), .Y (n_288));
  sky130_fd_sc_hd__nor2_1 g23323(.A (n_240), .B (n_273), .Y (n_285));
  sky130_fd_sc_hd__nand3_1 g23324(.A (n_260), .B (n_254), .C (n_199),
       .Y (n_284));
  sky130_fd_sc_hd__nand2_1 g23325(.A (n_275), .B (n_174), .Y (n_283));
  sky130_fd_sc_hd__nand3_1 g23326(.A (n_256), .B (n_257), .C (n_3), .Y
       (n_287));
  sky130_fd_sc_hd__nor2_1 g23327(.A (n_270), .B (n_7), .Y (n_282));
  sky130_fd_sc_hd__o21a_1 g23328(.A1 (n_170), .A2 (n_14), .B1 (n_164),
       .X (n_281));
  sky130_fd_sc_hd__nand2_4 g23329(.A (n_274), .B (n_176), .Y (n_286));
  sky130_fd_sc_hd__xnor2_1 g23331(.A (n_269), .B (n_191), .Y (n_280));
  sky130_fd_sc_hd__o21ai_1 g23332(.A1 (n_189), .A2 (n_14), .B1 (n_208),
       .Y (n_279));
  sky130_fd_sc_hd__nand2_1 g23333(.A (n_267), .B (n_271), .Y (n_278));
  sky130_fd_sc_hd__nand2_1 g23335(.A (n_275), .B (n_263), .Y (n_277));
  sky130_fd_sc_hd__o21ai_1 g23336(.A1 (n_170), .A2 (n_268), .B1
       (n_241), .Y (result_d[0]));
  sky130_fd_sc_hd__nand3_1 g23337(.A (n_40), .B (n_269), .C (n_176), .Y
       (n_276));
  sky130_fd_sc_hd__nand2_2 g23338(.A (n_190), .B (n_227), .Y (n_274));
  sky130_fd_sc_hd__o21ai_1 g23339(.A1 (n_174), .A2 (n_253), .B1
       (n_148), .Y (n_273));
  sky130_fd_sc_hd__nand2_2 g23340(.A (n_260), .B (n_199), .Y (n_275));
  sky130_fd_sc_hd__a21oi_1 g23341(.A1 (n_244), .A2 (n_30), .B1 (n_41),
       .Y (n_272));
  sky130_fd_sc_hd__o21a_1 g23342(.A1 (n_197), .A2 (n_248), .B1 (n_9),
       .X (n_271));
  sky130_fd_sc_hd__nand3_1 g23343(.A (n_264), .B (n_223), .C (n_221),
       .Y (n_270));
  sky130_fd_sc_hd__inv_2 g23344(.A (n_227), .Y (n_269));
  sky130_fd_sc_hd__nand2_1 g23345(.A (n_244), .B (n_220), .Y (n_267));
  sky130_fd_sc_hd__nand2_1 g23346(.A (n_245), .B (n_218), .Y (n_266));
  sky130_fd_sc_hd__nand2_1 g23347(.A (n_244), .B (n_218), .Y (n_265));
  sky130_fd_sc_hd__nand2_1 g23348(.A (n_41), .B (n_188), .Y (n_264));
  sky130_fd_sc_hd__and3_1 g23349(.A (n_174), .B (n_234), .C (n_76), .X
       (n_263));
  sky130_fd_sc_hd__nor2_2 g23350(.A (n_242), .B (n_239), .Y (n_268));
  sky130_fd_sc_hd__inv_2 g23351(.A (n_261), .Y (n_262));
  sky130_fd_sc_hd__inv_1 g23353(.A (n_258), .Y (n_259));
  sky130_fd_sc_hd__nand3_1 g23354(.A (n_175), .B (n_40), .C (n_171), .Y
       (n_257));
  sky130_fd_sc_hd__nand3_1 g23355(.A (n_199), .B (n_197), .C (n_198),
       .Y (n_261));
  sky130_fd_sc_hd__nand3_1 g23357(.A (n_237), .B (n_175), .C (n_171),
       .Y (n_256));
  sky130_fd_sc_hd__nand2_2 g23358(.A (n_250), .B (n_175), .Y (n_260));
  sky130_fd_sc_hd__nand2_2 g23360(.A (n_246), .B (n_228), .Y (n_258));
  sky130_fd_sc_hd__inv_1 g23361(.A (n_252), .Y (n_255));
  sky130_fd_sc_hd__clkinv_1 g23362(.A (n_253), .Y (n_254));
  sky130_fd_sc_hd__nand2_1 g23363(.A (n_198), .B (n_17), .Y (n_252));
  sky130_fd_sc_hd__nand2_1 g23364(.A (n_16), .B (n_40), .Y (n_251));
  sky130_fd_sc_hd__nand2_1 g23367(.A (n_197), .B (n_235), .Y (n_250));
  sky130_fd_sc_hd__nand2_1 g23368(.A (n_234), .B (n_80), .Y (n_249));
  sky130_fd_sc_hd__nand2_1 g23369(.A (n_235), .B (n_76), .Y (n_248));
  sky130_fd_sc_hd__nor2_1 g23370(.A (n_75), .B (n_199), .Y (n_247));
  sky130_fd_sc_hd__nand2_1 g23371(.A (n_201), .B (n_76), .Y (n_253));
  sky130_fd_sc_hd__inv_2 g23372(.A (n_238), .Y (n_246));
  sky130_fd_sc_hd__xnor2_1 g23375(.A (n_154), .B (n_192), .Y (n_243));
  sky130_fd_sc_hd__nand3_1 g23376(.A (n_222), .B (n_214), .C (n_213),
       .Y (n_242));
  sky130_fd_sc_hd__a21oi_1 g23377(.A1 (n_218), .A2 (n_173), .B1
       (n_224), .Y (n_241));
  sky130_fd_sc_hd__o21ai_1 g23378(.A1 (n_172), .A2 (n_219), .B1
       (n_165), .Y (n_240));
  sky130_fd_sc_hd__o21ai_2 g23379(.A1 (n_66), .A2 (n_203), .B1 (n_233),
       .Y (n_239));
  sky130_fd_sc_hd__nand2_1 g23380(.A (n_225), .B (n_231), .Y (n_238));
  sky130_fd_sc_hd__o21ai_2 g23381(.A1 (n_31), .A2 (n_217), .B1 (n_230),
       .Y (n_245));
  sky130_fd_sc_hd__o2bb2ai_1 g23382(.A1_N (n_67), .A2_N (n_204), .B1
       (n_1), .B2 (n_193), .Y (n_41));
  sky130_fd_sc_hd__nand2_2 g23383(.A (n_229), .B (n_163), .Y (n_244));
  sky130_fd_sc_hd__inv_2 g23388(.A (n_198), .Y (n_237));
  sky130_fd_sc_hd__clkbuf_1 g23389(.A (n_198), .X (n_236));
  sky130_fd_sc_hd__inv_2 g23390(.A (n_171), .Y (n_235));
  sky130_fd_sc_hd__inv_1 g23391(.A (n_201), .Y (n_234));
  sky130_fd_sc_hd__nand2_1 g23393(.A (n_195), .B (n_79), .Y (n_233));
  sky130_fd_sc_hd__nand2_1 g23394(.A (n_204), .B (n_79), .Y (n_232));
  sky130_fd_sc_hd__nand2_1 g23395(.A (n_202), .B (n_79), .Y (n_231));
  sky130_fd_sc_hd__nand2_1 g23396(.A (n_200), .B (n_31), .Y (n_230));
  sky130_fd_sc_hd__nand2_1 g23397(.A (n_205), .B (n_31), .Y (n_229));
  sky130_fd_sc_hd__nand2_1 g23398(.A (n_216), .B (n_71), .Y (n_228));
  sky130_fd_sc_hd__nand2_1 g23400(.A (n_216), .B (n_210), .Y (n_226));
  sky130_fd_sc_hd__nand2_1 g23401(.A (n_200), .B (n_67), .Y (n_225));
  sky130_fd_sc_hd__o2111ai_1 g23402(.A1 (n_24), .A2 (n_100), .B1
       (n_150), .C1 (n_149), .D1 (n_168), .Y (n_224));
  sky130_fd_sc_hd__nand2_1 g23403(.A (n_216), .B (n_207), .Y (n_223));
  sky130_fd_sc_hd__nand2_1 g23404(.A (n_200), .B (n_71), .Y (n_222));
  sky130_fd_sc_hd__a21oi_1 g23406(.A1 (n_151), .A2 (A[6]), .B1 (n_194),
       .Y (n_221));
  sky130_fd_sc_hd__nand2_2 g23407(.A (n_212), .B (n_181), .Y (n_227));
  sky130_fd_sc_hd__inv_2 g23408(.A (n_219), .Y (n_220));
  sky130_fd_sc_hd__inv_1 g23409(.A (n_216), .Y (n_217));
  sky130_fd_sc_hd__nand3_1 g23410(.A (n_138), .B (n_82), .C (n_30), .Y
       (n_215));
  sky130_fd_sc_hd__nand3_1 g23411(.A (n_138), .B (n_72), .C (n_28), .Y
       (n_214));
  sky130_fd_sc_hd__nand3_1 g23412(.A (n_144), .B (n_72), .C (n_27), .Y
       (n_213));
  sky130_fd_sc_hd__nand2_1 g23413(.A (n_186), .B (n_155), .Y (n_212));
  sky130_fd_sc_hd__nand2_1 g23414(.A (n_188), .B (n_30), .Y (n_211));
  sky130_fd_sc_hd__nor2_1 g23415(.A (n_1), .B (n_189), .Y (n_210));
  sky130_fd_sc_hd__o2111a_1 g23416(.A1 (A[1]), .A2 (n_106), .B1 (n_2),
       .C1 (n_109), .D1 (n_105), .X (n_209));
  sky130_fd_sc_hd__o2111a_1 g23417(.A1 (A[4]), .A2 (n_112), .B1 (n_95),
       .C1 (n_108), .D1 (n_104), .X (n_208));
  sky130_fd_sc_hd__nor2_1 g23418(.A (n_1), .B (n_170), .Y (n_207));
  sky130_fd_sc_hd__o21ai_1 g23419(.A1 (A[2]), .A2 (n_107), .B1 (n_166),
       .Y (n_206));
  sky130_fd_sc_hd__nand2_1 g23420(.A (n_169), .B (n_29), .Y (n_219));
  sky130_fd_sc_hd__nor2_1 g23421(.A (n_30), .B (n_189), .Y (n_218));
  sky130_fd_sc_hd__nand2_2 g23422(.A (n_160), .B (n_177), .Y (n_216));
  sky130_fd_sc_hd__inv_2 g23423(.A (n_202), .Y (n_203));
  sky130_fd_sc_hd__buf_1 g23425(.A (n_197), .X (n_196));
  sky130_fd_sc_hd__nand2_1 g23426(.A (n_179), .B (n_183), .Y (n_195));
  sky130_fd_sc_hd__o2bb2ai_1 g23427(.A1_N (n_36), .A2_N (n_147), .B1
       (A[6]), .B2 (n_100), .Y (n_194));
  sky130_fd_sc_hd__mux2i_1 g23428(.A0 (n_139), .A1 (n_157), .S (n_55),
       .Y (n_193));
  sky130_fd_sc_hd__nand2_1 g23429(.A (n_184), .B (n_187), .Y (n_205));
  sky130_fd_sc_hd__o21ai_2 g23430(.A1 (n_28), .A2 (n_141), .B1 (n_167),
       .Y (n_204));
  sky130_fd_sc_hd__nand2_1 g23431(.A (n_185), .B (n_178), .Y (n_202));
  sky130_fd_sc_hd__xnor2_1 g23432(.A (A[1]), .B (n_156), .Y (n_192));
  sky130_fd_sc_hd__xnor2_1 g23433(.A (n_59), .B (n_135), .Y (n_191));
  sky130_fd_sc_hd__xnor3_1 g23434(.A (A[7]), .B (n_35), .C (n_39), .X
       (n_201));
  sky130_fd_sc_hd__nand2_2 g23435(.A (n_180), .B (n_182), .Y (n_200));
  sky130_fd_sc_hd__xnor3_1 g23436(.A (A[6]), .B (n_36), .C (n_38), .X
       (n_199));
  sky130_fd_sc_hd__xnor3_2 g23437(.A (A[4]), .B (n_21), .C (n_39), .X
       (n_198));
  sky130_fd_sc_hd__xnor3_1 g23439(.A (A[5]), .B (n_19), .C (n_92), .X
       (n_197));
  sky130_fd_sc_hd__inv_2 g23440(.A (n_189), .Y (n_188));
  sky130_fd_sc_hd__nand2_1 g23441(.A (n_143), .B (n_27), .Y (n_187));
  sky130_fd_sc_hd__nand2_1 g23442(.A (n_154), .B (n_58), .Y (n_186));
  sky130_fd_sc_hd__nand2_1 g23444(.A (n_157), .B (n_27), .Y (n_185));
  sky130_fd_sc_hd__nand2_1 g23445(.A (n_144), .B (n_55), .Y (n_184));
  sky130_fd_sc_hd__nand2_1 g23446(.A (n_145), .B (n_27), .Y (n_183));
  sky130_fd_sc_hd__nand2_1 g23447(.A (n_142), .B (n_27), .Y (n_182));
  sky130_fd_sc_hd__nand2_1 g23448(.A (n_153), .B (A[1]), .Y (n_181));
  sky130_fd_sc_hd__nand2_2 g23450(.A (n_143), .B (n_55), .Y (n_180));
  sky130_fd_sc_hd__nand2_1 g23451(.A (n_139), .B (n_55), .Y (n_179));
  sky130_fd_sc_hd__nand2_1 g23452(.A (n_140), .B (n_55), .Y (n_178));
  sky130_fd_sc_hd__nand2_1 g23453(.A (n_134), .B (n_59), .Y (n_190));
  sky130_fd_sc_hd__nand2_1 g23454(.A (n_144), .B (n_27), .Y (n_177));
  sky130_fd_sc_hd__nand2_1 g23455(.A (n_159), .B (n_37), .Y (n_189));
  sky130_fd_sc_hd__inv_1 g23456(.A (n_172), .Y (n_173));
  sky130_fd_sc_hd__inv_2 g23457(.A (n_169), .Y (n_170));
  sky130_fd_sc_hd__a22oi_1 g23458(.A1 (n_94), .A2 (n_76), .B1 (n_64),
       .B2 (n_129), .Y (n_168));
  sky130_fd_sc_hd__nand2_1 g23459(.A (n_142), .B (n_28), .Y (n_167));
  sky130_fd_sc_hd__a32oi_1 g23460(.A1 (n_99), .A2 (n_29), .A3 (A[2]),
       .B1 (n_103), .B2 (n_64), .Y (n_166));
  sky130_fd_sc_hd__a32oi_1 g23461(.A1 (n_99), .A2 (n_35), .A3 (A[7]),
       .B1 (n_113), .B2 (n_44), .Y (n_165));
  sky130_fd_sc_hd__a32oi_1 g23462(.A1 (n_99), .A2 (n_26), .A3 (n_18),
       .B1 (n_115), .B2 (n_43), .Y (n_164));
  sky130_fd_sc_hd__nand2_1 g23463(.A (n_138), .B (n_63), .Y (n_163));
  sky130_fd_sc_hd__nor2_1 g23464(.A (n_50), .B (n_146), .Y (n_162));
  sky130_fd_sc_hd__nor2_1 g23465(.A (n_44), .B (n_133), .Y (n_161));
  sky130_fd_sc_hd__nand2_2 g23466(.A (n_135), .B (A[2]), .Y (n_176));
  sky130_fd_sc_hd__nand2_1 g23467(.A (n_138), .B (n_55), .Y (n_160));
  sky130_fd_sc_hd__nand2_1 g23468(.A (n_136), .B (A[5]), .Y (n_175));
  sky130_fd_sc_hd__nand2_1 g23469(.A (n_131), .B (A[6]), .Y (n_174));
  sky130_fd_sc_hd__nand2_1 g23470(.A (n_138), .B (n_82), .Y (n_172));
  sky130_fd_sc_hd__nand2_2 g23471(.A (n_132), .B (n_18), .Y (n_40));
  sky130_fd_sc_hd__nand2_2 g23472(.A (n_137), .B (A[4]), .Y (n_171));
  sky130_fd_sc_hd__nor2_1 g23473(.A (n_37), .B (n_158), .Y (n_169));
  sky130_fd_sc_hd__inv_1 g23474(.A (n_158), .Y (n_159));
  sky130_fd_sc_hd__clkbuf_1 g23475(.A (n_155), .X (n_156));
  sky130_fd_sc_hd__inv_2 g23476(.A (n_153), .Y (n_154));
  sky130_fd_sc_hd__a21oi_1 g23477(.A1 (n_99), .A2 (n_20), .B1 (n_111),
       .Y (n_152));
  sky130_fd_sc_hd__o21ai_1 g23478(.A1 (n_36), .A2 (n_98), .B1 (n_102),
       .Y (n_151));
  sky130_fd_sc_hd__o21ai_1 g23479(.A1 (n_24), .A2 (n_28), .B1 (n_101),
       .Y (n_150));
  sky130_fd_sc_hd__nand2_1 g23480(.A (n_99), .B (n_94), .Y (n_149));
  sky130_fd_sc_hd__a31oi_1 g23481(.A1 (n_64), .A2 (A[7]), .A3 (n_34),
       .B1 (n_110), .Y (n_148));
  sky130_fd_sc_hd__o221ai_1 g23482(.A1 (A[6]), .A2 (n_77), .B1 (n_60),
       .B2 (n_65), .C1 (n_102), .Y (n_147));
  sky130_fd_sc_hd__o2bb2ai_1 g23483(.A1_N (n_73), .A2_N (n_84), .B1
       (n_18), .B2 (n_69), .Y (n_146));
  sky130_fd_sc_hd__o21ai_1 g23484(.A1 (n_48), .A2 (n_37), .B1 (n_120),
       .Y (n_145));
  sky130_fd_sc_hd__nand3_1 g23485(.A (n_8), .B (n_68), .C (n_50), .Y
       (n_158));
  sky130_fd_sc_hd__o21ai_2 g23486(.A1 (n_59), .A2 (n_89), .B1 (n_126),
       .Y (n_157));
  sky130_fd_sc_hd__o22ai_2 g23487(.A1 (n_74), .A2 (n_81), .B1 (n_33),
       .B2 (n_96), .Y (n_155));
  sky130_fd_sc_hd__nand2_2 g23488(.A (n_83), .B (n_70), .Y (n_153));
  sky130_fd_sc_hd__inv_2 g23489(.A (n_140), .Y (n_141));
  sky130_fd_sc_hd__inv_2 g23492(.A (n_134), .Y (n_135));
  sky130_fd_sc_hd__inv_2 g23493(.A (n_130), .Y (n_134));
  sky130_fd_sc_hd__o21ai_2 g23494(.A1 (n_58), .A2 (n_88), .B1 (n_127),
       .Y (n_144));
  sky130_fd_sc_hd__o21ai_2 g23495(.A1 (n_61), .A2 (n_87), .B1 (n_116),
       .Y (n_143));
  sky130_fd_sc_hd__o21ai_1 g23496(.A1 (n_42), .A2 (n_89), .B1 (n_118),
       .Y (n_142));
  sky130_fd_sc_hd__o21ai_2 g23497(.A1 (n_43), .A2 (n_89), .B1 (n_117),
       .Y (n_140));
  sky130_fd_sc_hd__o21ai_1 g23498(.A1 (n_58), .A2 (n_37), .B1 (n_119),
       .Y (n_139));
  sky130_fd_sc_hd__nand2_2 g23499(.A (n_123), .B (n_121), .Y (n_138));
  sky130_fd_sc_hd__xor2_1 g23500(.A (n_34), .B (n_39), .X (n_133));
  sky130_fd_sc_hd__o21ai_2 g23501(.A1 (n_25), .A2 (n_38), .B1 (n_122),
       .Y (n_132));
  sky130_fd_sc_hd__o2bb2ai_1 g23502(.A1_N (n_36), .A2_N (n_39), .B1
       (n_36), .B2 (n_39), .Y (n_131));
  sky130_fd_sc_hd__nand2_1 g23503(.A (n_128), .B (n_125), .Y (n_137));
  sky130_fd_sc_hd__o2bb2ai_1 g23504(.A1_N (n_19), .A2_N (n_39), .B1
       (n_19), .B2 (n_39), .Y (n_136));
  sky130_fd_sc_hd__o2bb2ai_2 g23505(.A1_N (n_57), .A2_N (n_91), .B1
       (n_29), .B2 (n_91), .Y (n_130));
  sky130_fd_sc_hd__inv_1 g23506(.A (n_70), .Y (n_129));
  sky130_fd_sc_hd__nand2_1 g23507(.A (n_93), .B (n_22), .Y (n_128));
  sky130_fd_sc_hd__nand2_1 g23508(.A (n_86), .B (A[6]), .Y (n_127));
  sky130_fd_sc_hd__nand2_1 g23509(.A (n_87), .B (A[5]), .Y (n_126));
  sky130_fd_sc_hd__nand2_1 g23510(.A (n_38), .B (n_21), .Y (n_125));
  sky130_fd_sc_hd__nand2_1 g23511(.A (n_101), .B (n_19), .Y (n_124));
  sky130_fd_sc_hd__nand2_1 g23512(.A (n_88), .B (A[7]), .Y (n_123));
  sky130_fd_sc_hd__nand2_1 g23513(.A (n_38), .B (n_25), .Y (n_122));
  sky130_fd_sc_hd__nand2_1 g23514(.A (n_37), .B (n_24), .Y (n_121));
  sky130_fd_sc_hd__nand2_1 g23515(.A (n_37), .B (A[7]), .Y (n_120));
  sky130_fd_sc_hd__nand2_1 g23516(.A (n_87), .B (A[6]), .Y (n_119));
  sky130_fd_sc_hd__nand2_1 g23517(.A (n_89), .B (n_18), .Y (n_118));
  sky130_fd_sc_hd__nand2_1 g23518(.A (n_89), .B (A[4]), .Y (n_117));
  sky130_fd_sc_hd__nand2_1 g23519(.A (n_87), .B (A[2]), .Y (n_116));
  sky130_fd_sc_hd__o21ai_1 g23520(.A1 (n_26), .A2 (n_77), .B1 (n_100),
       .Y (n_115));
  sky130_fd_sc_hd__and2_1 g23521(.A (n_100), .B (n_97), .X (n_114));
  sky130_fd_sc_hd__o21ai_1 g23522(.A1 (n_35), .A2 (n_77), .B1 (n_100),
       .Y (n_113));
  sky130_fd_sc_hd__o21a_1 g23523(.A1 (n_22), .A2 (n_77), .B1 (n_100),
       .X (n_112));
  sky130_fd_sc_hd__o21ai_1 g23524(.A1 (n_20), .A2 (n_65), .B1 (n_102),
       .Y (n_111));
  sky130_fd_sc_hd__a21oi_1 g23525(.A1 (n_35), .A2 (n_44), .B1 (n_102),
       .Y (n_110));
  sky130_fd_sc_hd__o21ai_1 g23526(.A1 (A[1]), .A2 (n_32), .B1 (n_101),
       .Y (n_109));
  sky130_fd_sc_hd__o21ai_1 g23527(.A1 (A[4]), .A2 (n_21), .B1 (n_101),
       .Y (n_108));
  sky130_fd_sc_hd__o21a_1 g23528(.A1 (n_29), .A2 (n_77), .B1 (n_100),
       .X (n_107));
  sky130_fd_sc_hd__o21a_1 g23529(.A1 (n_33), .A2 (n_77), .B1 (n_100),
       .X (n_106));
  sky130_fd_sc_hd__nand3_1 g23530(.A (n_99), .B (n_33), .C (A[1]), .Y
       (n_105));
  sky130_fd_sc_hd__nand3_1 g23531(.A (n_99), .B (n_22), .C (A[4]), .Y
       (n_104));
  sky130_fd_sc_hd__maj3_1 g23532(.A (A[2]), .B (B[2]), .C (op_sel[0]),
       .X (n_103));
  sky130_fd_sc_hd__inv_2 g23533(.A (n_102), .Y (n_101));
  sky130_fd_sc_hd__inv_1 g23536(.A (n_99), .Y (n_98));
  sky130_fd_sc_hd__nand2_1 g23537(.A (n_78), .B (n_19), .Y (n_97));
  sky130_fd_sc_hd__nor2_2 g23538(.A (n_62), .B (n_81), .Y (n_96));
  sky130_fd_sc_hd__nand3_1 g23539(.A (n_64), .B (A[4]), .C (n_21), .Y
       (n_95));
  sky130_fd_sc_hd__nand3_1 g23540(.A (n_46), .B (op_sel[0]), .C (n_49),
       .Y (n_102));
  sky130_fd_sc_hd__nand2_2 g23541(.A (n_78), .B (op_sel[0]), .Y
       (n_100));
  sky130_fd_sc_hd__nor2_4 g23542(.A (op_sel[0]), .B (n_77), .Y (n_99));
  sky130_fd_sc_hd__inv_2 g23544(.A (n_39), .Y (n_93));
  sky130_fd_sc_hd__buf_6 g23546(.A (n_90), .X (n_39));
  sky130_fd_sc_hd__inv_2 g23547(.A (n_91), .Y (n_92));
  sky130_fd_sc_hd__inv_4 g23550(.A (n_91), .Y (n_38));
  sky130_fd_sc_hd__clkinv_4 g23551(.A (n_90), .Y (n_91));
  sky130_fd_sc_hd__inv_2 g23552(.A (n_89), .Y (n_88));
  sky130_fd_sc_hd__inv_2 g23553(.A (n_85), .Y (n_89));
  sky130_fd_sc_hd__inv_4 g23554(.A (n_86), .Y (n_87));
  sky130_fd_sc_hd__inv_2 g23556(.A (n_86), .Y (n_37));
  sky130_fd_sc_hd__buf_6 g23558(.A (n_85), .X (n_86));
  sky130_fd_sc_hd__o21ai_1 g23559(.A1 (n_18), .A2 (n_47), .B1 (n_69),
       .Y (n_84));
  sky130_fd_sc_hd__nand4_1 g23562(.A (n_53), .B (i_op_sel[0]), .C
       (n_56), .D (n_52), .Y (n_83));
  sky130_fd_sc_hd__xnor2_1 g23563(.A (n_24), .B (n_27), .Y (n_94));
  sky130_fd_sc_hd__nand3_2 g23564(.A (n_51), .B (n_54), .C
       (i_op_sel[0]), .Y (n_90));
  sky130_fd_sc_hd__nand3_2 g23565(.A (i_op_sel[0]), .B (i_op_sel[2]),
       .C (i_op_sel[1]), .Y (n_85));
  sky130_fd_sc_hd__clkinv_1 g23566(.A (n_81), .Y (n_80));
  sky130_fd_sc_hd__inv_2 g23567(.A (n_1), .Y (n_79));
  sky130_fd_sc_hd__clkinv_2 g23568(.A (n_78), .Y (n_77));
  sky130_fd_sc_hd__inv_2 g23569(.A (n_76), .Y (n_75));
  sky130_fd_sc_hd__nand2_1 g23570(.A (i_op_sel[0]), .B (n_33), .Y
       (n_74));
  sky130_fd_sc_hd__nor2_1 g23571(.A (n_32), .B (n_55), .Y (n_82));
  sky130_fd_sc_hd__nand2_1 g23572(.A (n_23), .B (op_sel[0]), .Y (n_73));
  sky130_fd_sc_hd__nand2_2 g23573(.A (n_53), .B (n_52), .Y (n_81));
  sky130_fd_sc_hd__and2_4 g23575(.A (n_45), .B (op_sel[2]), .X (n_78));
  sky130_fd_sc_hd__nor2_2 g23576(.A (n_50), .B (n_23), .Y (n_76));
  sky130_fd_sc_hd__inv_1 g23577(.A (n_68), .Y (n_69));
  sky130_fd_sc_hd__inv_1 g23578(.A (n_67), .Y (n_66));
  sky130_fd_sc_hd__inv_2 g23579(.A (n_65), .Y (n_64));
  sky130_fd_sc_hd__nor2_1 g23580(.A (n_31), .B (n_28), .Y (n_63));
  sky130_fd_sc_hd__nor2_1 g23581(.A (n_31), .B (n_29), .Y (n_72));
  sky130_fd_sc_hd__nor2_1 g23582(.A (n_32), .B (n_29), .Y (n_71));
  sky130_fd_sc_hd__nand2_1 g23583(.A (A[0]), .B (B[0]), .Y (n_70));
  sky130_fd_sc_hd__and2_1 g23584(.A (n_26), .B (n_46), .X (n_68));
  sky130_fd_sc_hd__nor2_1 g23585(.A (n_33), .B (B[2]), .Y (n_67));
  sky130_fd_sc_hd__nand2_1 g23586(.A (n_46), .B (n_49), .Y (n_65));
  sky130_fd_sc_hd__inv_1 g23587(.A (i_op_sel[0]), .Y (n_62));
  sky130_fd_sc_hd__clkbuf_1 g23590(.A (B[6]), .X (n_36));
  sky130_fd_sc_hd__inv_1 g23593(.A (n_35), .Y (n_34));
  sky130_fd_sc_hd__clkinv_1 g23595(.A (B[7]), .Y (n_35));
  sky130_fd_sc_hd__inv_2 g23596(.A (A[5]), .Y (n_61));
  sky130_fd_sc_hd__inv_1 g23597(.A (A[6]), .Y (n_60));
  sky130_fd_sc_hd__inv_2 g23598(.A (A[2]), .Y (n_59));
  sky130_fd_sc_hd__inv_2 g23599(.A (A[1]), .Y (n_58));
  sky130_fd_sc_hd__buf_1 g23611(.A (n_33), .X (n_31));
  sky130_fd_sc_hd__inv_2 g23613(.A (n_33), .Y (n_32));
  sky130_fd_sc_hd__inv_2 g23614(.A (B[1]), .Y (n_33));
  sky130_fd_sc_hd__inv_2 g23620(.A (n_29), .Y (n_30));
  sky130_fd_sc_hd__inv_2 g23621(.A (B[2]), .Y (n_29));
  sky130_fd_sc_hd__inv_2 g23623(.A (B[2]), .Y (n_57));
  sky130_fd_sc_hd__inv_2 g23624(.A (B[0]), .Y (n_56));
  sky130_fd_sc_hd__inv_2 g23632(.A (n_27), .Y (n_55));
  sky130_fd_sc_hd__inv_4 g23637(.A (n_28), .Y (n_27));
  sky130_fd_sc_hd__buf_4 g23638(.A (B[0]), .X (n_28));
  sky130_fd_sc_hd__clkinv_2 g23639(.A (i_op_sel[2]), .Y (n_54));
  sky130_fd_sc_hd__clkinv_1 g23640(.A (i_op_sel[2]), .Y (n_53));
  sky130_fd_sc_hd__inv_2 g23641(.A (i_op_sel[1]), .Y (n_52));
  sky130_fd_sc_hd__inv_2 g23642(.A (i_op_sel[1]), .Y (n_51));
  sky130_fd_sc_hd__inv_2 g23646(.A (n_26), .Y (n_25));
  sky130_fd_sc_hd__inv_2 g23647(.A (B[3]), .Y (n_26));
  sky130_fd_sc_hd__inv_2 g23648(.A (n_49), .Y (n_50));
  sky130_fd_sc_hd__inv_2 g23649(.A (op_sel[2]), .Y (n_49));
  sky130_fd_sc_hd__inv_2 g23651(.A (n_24), .Y (n_48));
  sky130_fd_sc_hd__buf_1 g23652(.A (A[0]), .X (n_24));
  sky130_fd_sc_hd__inv_2 g23653(.A (n_23), .Y (n_47));
  sky130_fd_sc_hd__clkbuf_2 g23656(.A (n_46), .X (n_23));
  sky130_fd_sc_hd__inv_2 g23657(.A (n_45), .Y (n_46));
  sky130_fd_sc_hd__clkinv_1 g23658(.A (op_sel[1]), .Y (n_45));
  sky130_fd_sc_hd__inv_2 g23664(.A (n_22), .Y (n_21));
  sky130_fd_sc_hd__clkinv_1 g23665(.A (B[4]), .Y (n_22));
  sky130_fd_sc_hd__inv_2 g23670(.A (n_20), .Y (n_19));
  sky130_fd_sc_hd__inv_2 g23671(.A (B[5]), .Y (n_20));
  sky130_fd_sc_hd__inv_2 g23672(.A (A[7]), .Y (n_44));
  sky130_fd_sc_hd__inv_2 g23673(.A (n_18), .Y (n_43));
  sky130_fd_sc_hd__clkbuf_2 g23677(.A (A[3]), .X (n_18));
  sky130_fd_sc_hd__clkinv_1 g23678(.A (A[4]), .Y (n_42));
  sky130_fd_sc_hd__inv_2 fopt23680(.A (n_16), .Y (n_17));
  sky130_fd_sc_hd__xnor3_1 g2(.A (A[3]), .B (n_26), .C (n_92), .X
       (n_16));
  sky130_fd_sc_hd__a21oi_2 g23685(.A1 (n_205), .A2 (n_67), .B1 (n_15),
       .Y (n_14));
  sky130_fd_sc_hd__nand2_1 g3(.A (n_215), .B (n_232), .Y (n_15));
  sky130_fd_sc_hd__inv_1 fopt23687(.A (n_12), .Y (n_13));
  sky130_fd_sc_hd__inv_2 fopt23688(.A (n_286), .Y (n_12));
  sky130_fd_sc_hd__o211a_1 g23689(.A1 (n_75), .A2 (n_243), .B1 (n_209),
       .C1 (n_226), .X (n_10));
  sky130_fd_sc_hd__o221a_1 g23690(.A1 (A[5]), .A2 (n_114), .B1 (n_61),
       .B2 (n_152), .C1 (n_124), .X (n_9));
  sky130_fd_sc_hd__and4bb_1 g23691(.A_N (B[7]), .B_N (B[6]), .C (n_22),
       .D (n_20), .X (n_8));
  sky130_fd_sc_hd__nor2b_1 g23692(.A (n_211), .B_N (n_244), .Y (n_7));
  sky130_fd_sc_hd__nor2b_1 g23693(.A (n_235), .B_N (n_197), .Y (n_6));
  sky130_fd_sc_hd__nand2b_1 g23694(.A_N (n_190), .B (n_40), .Y (n_5));
  sky130_fd_sc_hd__nand2b_1 g23695(.A_N (n_137), .B (n_42), .Y (n_4));
  sky130_fd_sc_hd__nand2b_1 g23696(.A_N (n_136), .B (n_61), .Y (n_3));
  sky130_fd_sc_hd__nand3b_1 g23697(.A_N (n_31), .B (n_64), .C (A[1]),
       .Y (n_2));
  sky130_fd_sc_hd__nand2b_1 g23698(.A_N (B[2]), .B (n_33), .Y (n_1));
  sky130_fd_sc_hd__nand2b_1 g23699(.A_N (n_17), .B (n_286), .Y (n_0));
endmodule

module synth_wrapper(clk, rst_n, A, B, op_sel, result, carry);
  input clk, rst_n;
  input [7:0] A, B;
  input [2:0] op_sel;
  output [7:0] result;
  output carry;
  wire clk, rst_n;
  wire [7:0] A, B;
  wire [2:0] op_sel;
  wire [7:0] result;
  wire carry;
  wire [7:0] A_reg;
  wire [7:0] B_reg;
  wire [2:0] op_sel_reg;
  wire carry_reg_84, \result_reg[0]_60 , \result_reg[1]_61 ,
       \result_reg[2]_62 , \result_reg[3]_63 , \result_reg[4]_64 ,
       \result_reg[5]_65 , \result_reg[6]_66 ;
  wire \result_reg[7]_67 ;
  alu_8bit dutty(.i_clk (clk), .i_rstn (rst_n), .i_a (A_reg), .i_b
       (B_reg), .i_op_sel (op_sel_reg), .o_result ({\result_reg[7]_67 ,
       \result_reg[6]_66 , \result_reg[5]_65 , \result_reg[4]_64 ,
       \result_reg[3]_63 , \result_reg[2]_62 , \result_reg[1]_61 ,
       \result_reg[0]_60 }), .o_carry (carry_reg_84));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[7] (.RESET_B (rst_n), .CLK
       (clk), .D (\result_reg[7]_67 ), .Q (result[7]));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[6] (.RESET_B (rst_n), .CLK
       (clk), .D (\result_reg[6]_66 ), .Q (result[6]));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[4] (.RESET_B (rst_n), .CLK
       (clk), .D (\result_reg[4]_64 ), .Q (result[4]));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[0] (.RESET_B (rst_n), .CLK
       (clk), .D (\result_reg[0]_60 ), .Q (result[0]));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[2] (.RESET_B (rst_n), .CLK
       (clk), .D (\result_reg[2]_62 ), .Q (result[2]));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[3] (.RESET_B (rst_n), .CLK
       (clk), .D (\result_reg[3]_63 ), .Q (result[3]));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[5] (.RESET_B (rst_n), .CLK
       (clk), .D (\result_reg[5]_65 ), .Q (result[5]));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[1] (.RESET_B (rst_n), .CLK
       (clk), .D (\result_reg[1]_61 ), .Q (result[1]));
  sky130_fd_sc_hd__dfrtp_1 carry_reg(.RESET_B (rst_n), .CLK (clk), .D
       (carry_reg_84), .Q (carry));
  sky130_fd_sc_hd__dfrtp_1 \A_reg_reg[6] (.RESET_B (rst_n), .CLK (clk),
       .D (A[6]), .Q (A_reg[6]));
  sky130_fd_sc_hd__dfrtp_1 \A_reg_reg[7] (.RESET_B (rst_n), .CLK (clk),
       .D (A[7]), .Q (A_reg[7]));
  sky130_fd_sc_hd__dfrtp_1 \B_reg_reg[5] (.RESET_B (rst_n), .CLK (clk),
       .D (B[5]), .Q (B_reg[5]));
  sky130_fd_sc_hd__dfrtp_1 \A_reg_reg[4] (.RESET_B (rst_n), .CLK (clk),
       .D (A[4]), .Q (A_reg[4]));
  sky130_fd_sc_hd__dfrtp_1 \A_reg_reg[1] (.RESET_B (rst_n), .CLK (clk),
       .D (A[1]), .Q (A_reg[1]));
  sky130_fd_sc_hd__dfrtp_1 \A_reg_reg[5] (.RESET_B (rst_n), .CLK (clk),
       .D (A[5]), .Q (A_reg[5]));
  sky130_fd_sc_hd__dfrtp_1 \A_reg_reg[2] (.RESET_B (rst_n), .CLK (clk),
       .D (A[2]), .Q (A_reg[2]));
  sky130_fd_sc_hd__dfrtp_2 \op_sel_reg_reg[0] (.RESET_B (rst_n), .CLK
       (clk), .D (op_sel[0]), .Q (op_sel_reg[0]));
  sky130_fd_sc_hd__dfrtp_1 \B_reg_reg[4] (.RESET_B (rst_n), .CLK (clk),
       .D (B[4]), .Q (B_reg[4]));
  sky130_fd_sc_hd__dfrtp_1 \B_reg_reg[0] (.RESET_B (rst_n), .CLK (clk),
       .D (B[0]), .Q (B_reg[0]));
  sky130_fd_sc_hd__dfrtp_1 \B_reg_reg[2] (.RESET_B (rst_n), .CLK (clk),
       .D (B[2]), .Q (B_reg[2]));
  sky130_fd_sc_hd__dfrtp_1 \B_reg_reg[3] (.RESET_B (rst_n), .CLK (clk),
       .D (B[3]), .Q (B_reg[3]));
  sky130_fd_sc_hd__dfrtp_2 \op_sel_reg_reg[1] (.RESET_B (rst_n), .CLK
       (clk), .D (op_sel[1]), .Q (op_sel_reg[1]));
  sky130_fd_sc_hd__dfrtp_1 \B_reg_reg[1] (.RESET_B (rst_n), .CLK (clk),
       .D (B[1]), .Q (B_reg[1]));
  sky130_fd_sc_hd__dfrtp_1 \B_reg_reg[6] (.RESET_B (rst_n), .CLK (clk),
       .D (B[6]), .Q (B_reg[6]));
  sky130_fd_sc_hd__dfrtp_1 \B_reg_reg[7] (.RESET_B (rst_n), .CLK (clk),
       .D (B[7]), .Q (B_reg[7]));
  sky130_fd_sc_hd__dfrtp_1 \A_reg_reg[3] (.RESET_B (rst_n), .CLK (clk),
       .D (A[3]), .Q (A_reg[3]));
  sky130_fd_sc_hd__dfrtp_2 \op_sel_reg_reg[2] (.RESET_B (rst_n), .CLK
       (clk), .D (op_sel[2]), .Q (op_sel_reg[2]));
  sky130_fd_sc_hd__dfrtp_1 \A_reg_reg[0] (.RESET_B (rst_n), .CLK (clk),
       .D (A[0]), .Q (A_reg[0]));
endmodule

